app1/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.signin, name='login'),
    path('logout/', views.signout, name='logout'),
    path('home/', views.home, name='home'),
    path('customer_home/', views.customer_home, name='customer_home'),
    path('update-active-branch/', views.update_active_branch, name='update_active_branch'),
    path('set_language/', views.set_language, name='set_language'),
    path('customer-login/', views.customer_login, name='customer_login'),
    path('customer-logout/', views.customer_signout, name='customer_logout'),
    path('customer_change_password/', views.customer_change_password, name='customer_change_password'),
    path('access-denied/', views.access_denied, name='access_denied'),

    path('manage-permissions/', views.manage_permissions, name='manage_permissions'),

    path('customers-add/', views.customer_add, name='customer_add'),
    path('customers-list/', views.customer_list, name='customer_list'),
    path('customers-details/<int:id>/', views.customer_details, name='customer_details'),
    path('customers-edit/<int:id>/', views.customer_edit, name='customer_edit'),

    path('general-list/', views.general_list, name='general_list'),
    path('general-deposit/<int:id>/', views.general_deposit, name='general_deposit'),
    path('general-withdraw/<int:id>/', views.general_withdraw, name='general_withdraw'),
    path('general-transactions/<int:id>/', views.general_transaction_history, name='general_transaction_history'),
    path('general-deposit-search/', views.general_deposit_search, name='general_deposit_search'),
    path('general-withdraw-search/', views.general_withdraw_search, name='general_withdraw_search'),

    path('savings-list/', views.savings_list, name='savings_list'),
    path('savings-deposit/<int:id>/', views.savings_deposit, name='savings_deposit'),
    path('savings-withdraw/<int:id>/', views.savings_withdraw, name='savings_withdraw'),
    path('savings-transactions/<int:id>/', views.savings_transaction_history, name='savings_transaction_history'),
    path('savings-deposit-search/', views.savings_deposit_search, name='savings_deposit_search'),
    path('savings-withdraw-search/', views.savings_withdraw_search, name='savings_withdraw_search'),

    path('loan-search/', views.loan_search, name='loan_search'),
    path('loan-list/', views.loan_list, name='loan_list'),
    path('loan-create/<str:account_no>/', views.loan_create, name='loan_create'),
    path('loan-schedule/<int:loan_id>/', views.loan_schedule, name='loan_schedule'),
    path('loan-collection/<int:loan_id>/', views.loan_collection, name='loan_collection'),
    path('loan-transaction/<int:loan_id>/', views.loan_trans, name='loan_trans'),
    path('loan-fine/<int:loan_id>/', views.loan_fine, name='loan_fine'),
    path('loan-collection-search/', views.loan_collection_search, name='loan_collection_search'),
    path('loan-close-search/', views.loan_close_search, name='loan_close_search'),
    path('loan-close/<int:loan_id>/', views.loan_close, name='loan_close'),



    path('loan-cc-search/', views.loan_cc_search, name='loan_cc_search'),
    path('loan-cc-list/', views.loan_cc_list, name='loan_cc_list'),
    path('loan-cc-create/<str:account_no>/', views.loan_cc_create, name='loan_cc_create'),
    path('loan-cc-collection/<int:loan_id>/', views.loan_cc_collection, name='loan_cc_collection'),
    path('loan-cc-transaction/<int:loan_id>/', views.loan_cc_trans, name='loan_cc_trans'),
    path('loan-cc-collection-search/', views.loan_cc_collection_search, name='loan_cc_collection_search'),
    path('loan-cc-close-search/', views.loan_cc_close_search, name='loan_cc_close_search'),
    path('loan-cc-close/<int:loan_id>/', views.loan_cc_close, name='loan_cc_close'),


    path('loan-special-search/', views.loan_sp_search, name='loan_sp_search'),
    path('loan-special-list/', views.loan_sp_list, name='loan_sp_list'),
    path('loan-special-create/<str:account_no>/', views.loan_sp_create, name='loan_sp_create'),
    path('loan-special-collection/<int:loan_id>/', views.loan_sp_collection, name='loan_sp_collection'),
    path('loan-special-close-search/', views.loan_sp_close_search, name='loan_sp_close_search'),
    path('loan-special-close/<int:loan_id>/', views.loan_sp_close, name='loan_sp_close'),



    path('dps-search/', views.dps_search, name='dps_search'),
    path('dps-list/', views.dps_list, name='dps_list'),
    path('dps-create/<str:account_no>/', views.dps_create, name='dps_create'),
    path('dps-schedule/<int:id>/', views.dps_schedule, name='dps_schedule'),
    path('dps-deposit/<int:id>/', views.dps_deposit, name='dps_deposit'),
    path('dps-withdraw/<int:id>/', views.dps_withdraw, name='dps_withdraw'),
    path('dps-transaction/<int:id>/', views.dps_transaction, name='dps_transaction'),
    path('dps-deposit-search/', views.dps_deposit_search, name='dps_deposit_search'),
    path('dps-withdraw-search/', views.dps_withdraw_search, name='dps_withdraw_search'),
    path('dps-close-search/', views.dps_close_search, name='dps_close_search'),
    path('dps-close/<int:id>/', views.dps_close, name='dps_close'),

    path('fdr-search/', views.fdr_search, name='fdr_search'),
    path('fdr-list/', views.fdr_list, name='fdr_list'),
    path('fdr-create/<str:account_no>/', views.fdr_create, name='fdr_create'),
    path('fdr-deposit/<int:id>/', views.fdr_deposit, name='fdr_deposit'),
    path('fdr-withdraw/<int:id>/', views.fdr_withdraw, name='fdr_withdraw'),
    path('fdr-profit-withdraw/<int:id>/', views.fdr_profit_withdraw, name='fdr_profit_withdraw'),
    path('fdr-transactions/<int:id>/', views.fdr_transaction_history, name='fdr_transaction_history'),
    path('fdr-profit/<int:id>/', views.fdr_profit, name='fdr_profit'),
    path('fdr-deposit-search/', views.fdr_deposit_search, name='fdr_deposit_search'),
    path('fdr-profit-withdraw-search/', views.fdr_profit_withdraw_search, name='fdr_profit_withdraw_search'),
    path('fdr-balance-withdraw-search/', views.fdr_balance_withdraw_search, name='fdr_balance_withdraw_search'),
    path('fdr-close-search/', views.fdr_close_search, name='fdr_close_search'),
    path('fdr-close/<int:id>/', views.fdr_close, name='fdr_close'),

    path('share-list/', views.share_list, name='share_list'),
    path('share-create/<str:account_no>/', views.share_create, name='share_create'),
    path('share-search/', views.share_search, name='share_search'),
    path('share-deposit/<int:share_id>/', views.share_deposit, name='share_deposit'),
    path('share-deposit-search/', views.share_deposit_search, name='share_deposit_search'),
    path('share-withdraw-search/', views.share_withdraw_search, name='share_withdraw_search'),
    path('share-profit-withdraw-search/', views.share_profit_withdraw_search, name='share_profit_withdraw_search'),
    path('share-withdraw/<int:share_id>/', views.share_withdraw, name='share_withdraw'),
    path('share-transfer/<int:share_id>/', views.share_transfer, name='share_transfer'),
    path('share-profit-withdraw/<int:share_id>/', views.share_profit_withdraw, name='share_profit_withdraw'),
    path('share-transaction-history/<int:share_id>/', views.share_transaction_history, name='share_transaction_history'),

    path('bank_withdraw/', views.bank_withdraw, name='bank_withdraw'),
    path('bank_deposit/', views.bank_deposit, name='bank_deposit'),
    path('package/', views.package, name='package'),

    path('delete-search/', views.delete_search, name='delete_search'),
    path('delete-customer/<int:id>/', views.delete_customer, name='delete_customer'),
    path('delete-loan/<int:id>/', views.loan_delete, name='loan_delete'),
    path('delete-loan-cc/<int:id>/', views.loan_cc_delete, name='loan_cc_delete'),
    path('delete-loan-sp/<int:id>/', views.loan_sp_delete, name='loan_sp_delete'),
    path('delete-dps/<int:id>/', views.dps_delete, name='dps_delete'),
    path('delete-fdr/<int:id>/', views.fdr_delete, name='fdr_delete'),
    path('delete-share/<int:share_id>/', views.share_delete, name='share_delete'),

    path('somity_wise_dps_deposit/', views.somity_wise_dps_deposit, name='somity_wise_dps_deposit'),
    path('somity_wise_general_deposit/', views.somity_wise_general_deposit, name='somity_wise_general_deposit'),
    path('somity_wise_loan/', views.somity_wise_loan, name='somity_wise_loan'),
    path('common_collection/', views.common_collection, name='common_collection'),
]

project/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('app1.urls')),
    path('', include('primary_setup.urls')),
    path('', include('otrans.urls')),
    path('report/', include('report.urls')),
    path('sheet/', include('sheet.urls')),
    path('dashboard/', include('dashboard.urls')),
    path('sms/', include('sms.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

sms/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('sms_single/', views.sms_single, name='sms_single'),
    path('sms_bulk/', views.sms_bulk, name='sms_bulk'),
    path('sms_customer/', views.sms_customer, name='sms_customer'),
    path('sms_report/', views.sms_report, name='sms_report'),
]

report/models.py
from django.db import models
from django.utils import timezone
from primary_setup.models import Branch, CustomUser
from app1.models import ActiveBranch, Customer
import socket
from django.db.models import Sum

def get_ip_address():
    try:
        s = socket.socket(socket.AF_INET, socket.SOCK_DGRAM)
        s.connect(("8.8.8.8", 80))
        ip_address = s.getsockname()[0]
        s.close()
        return ip_address
    except Exception as e:
        return str(e)



class UserLog(models.Model):
    TRANSACTION_TYPE_CHOICES = [
        ('cash_in', 'Cash In'),
        ('cash_out', 'Cash Out'),
    ]
    CASHFLOW1_TYPE_CHOICES = [
        ('income', 'Income'),
        ('expense', 'Expense'),
    ]
    CASHFLOW2_TYPE_CHOICES = [
        ('receive', 'Receive'),
        ('payment', 'Payment'),
    ]

    branch = models.ForeignKey(Branch, on_delete=models.CASCADE, null=True, blank=True)
    customer = models.ForeignKey(Customer, on_delete=models.CASCADE, null=True, blank=True)
    processed_by = models.ForeignKey(CustomUser, on_delete=models.SET_NULL, null=True, blank=True)
    action = models.CharField(max_length=300, null=True, blank=True)
    logs_action = models.CharField(max_length=300, null=True, blank=True)

    transaction_type = models.CharField(max_length=10, choices=TRANSACTION_TYPE_CHOICES, null=True, blank=True)
    cashflow_type1 = models.CharField(max_length=10, choices=CASHFLOW1_TYPE_CHOICES, null=True, blank=True)
    cashflow_type2 = models.CharField(max_length=10, choices=CASHFLOW2_TYPE_CHOICES, null=True, blank=True)

    amount = models.DecimalField(max_digits=10, decimal_places=2, null=True, blank=True)
    # timestamp = models.DateTimeField(default=timezone.now)
    timestamp = models.DateTimeField(auto_now=True)
    ip_address = models.CharField(max_length=300, null=True, blank=True)
    description = models.CharField(max_length=300, null=True, blank=True)

    trx = models.BooleanField(null=True, blank=True)

    def save(self, *args, **kwargs):
        if not self.ip_address:
            self.ip_address = get_ip_address()
        if not self.branch and self.action not in [1, 2]:
            active_branch = ActiveBranch.objects.filter(user=self.processed_by).first()
            if active_branch:
                self.branch = active_branch.branch
            else:
                active_branch = None
                self.branch = active_branch
            
        if not self.logs_action:
            if not self.transaction_type and not self.cashflow_type1 and not self.cashflow_type2:
                self.transaction_type = 'cash_in'
                self.cashflow_type1 = 'income'
                self.cashflow_type2 = 'receive'
            if self.trx:
                self.transaction_type = 'cash_out'
                self.cashflow_type1 = 'expense'
                self.cashflow_type2 = 'payment'
        
        super().save(*args, **kwargs)

    def __str__(self):
        return f"{self.processed_by.username if self.processed_by else 'Unknown'} - {self.transaction_type} at {self.timestamp}"
    
    @staticmethod
    def get_sum_of_amounts_by_action():
        """
        Returns a dictionary with the sum of amounts for each unique action.
        """
        return UserLog.objects.values('action').annotate(total_amount=Sum('amount')).order_by('action')

templates/app1/fdr/fdr_bws.html
{% extends 'base.html' %}
{% load static %}
{% block title %}FDR Withdraw{% endblock %}
{% block style_links %}
<link rel="stylesheet" href="{% static 'app1/customer_details.css' %}">
<link rel="stylesheet" href="{% static 'app1/dps.css' %}">
{% endblock %}

{% block content %}
  <h2>FDR Balance Withdraw</h2>

  <div class="div1">
    <table>
        <tr>
            <th>Account No.</th>
            <td>{{ customer.account_no }}</td>
        </tr>
        <tr>
            <th>Customer Name</th>
            <td>{{ customer.customer_name }}</td>
        </tr>
        <tr>
            <th>Parents</th>
            <td>{{ customer.customer_father }}/{{ customer.customer_mother }}</td>
        </tr>
        <tr>
            <th>Mobile Number</th>
            <td>{{ customer.mobile_number }}</td>
        </tr>
        <tr>
            <th>Customer Type</th>
            <td>{{ customer.customer_type }}</td>
        </tr>
        <tr>
            <th>Somity/Group</th>
            <td>{{ customer.group }}</td>
        </tr>
        <tr>
            <th>Current Address</th>
            <td>{{ customer.current_village }}, {{ customer.current_post_office }}, {{ customer.current_thana }}, {{ customer.current_district }}</td>
        </tr>
        <tr>
            <th>Permanent Address</th>
            <td>{{ customer.permanent_village }}, {{ customer.permanent_post_office }}, {{ customer.permanent_thana }}, {{ customer.permanent_district }}</td>
        </tr>
    </table>
    
    <div class="img-container">
        {% if customer.profile_picture %}
        <div>
            <img src="{{ customer.profile_picture.url }}" class="centered-image">
        </div>
        {% endif %}
    </div>
</div>




<div class="div1">
  <div class="table-container">
      <table id="myTable" class="display" style="width:100%">
          <thead>
              <tr>
                  <td>Account No</td>
                  <td>Customer Name</td>
                  <td>Somity</td>
                  <td>Scheme</td>
                  <td>Type</td>
                  <td>Start Date</td>
                  <td>End Date</td>
                  <td>Opening Amount</td>
                  <td>Balance</td>
                  <td>Profit %</td>
                  <td>Total Profit</td>
                  <td>Profit Paid</td>
                  <td>Avaailabe Profit</td>
                  <td>Status</td>
                  <td>Action</td>
              </tr>
          </thead>
          <tbody>
            {% for fdr in fdrs %}
              <tr>
                  <td>{{ fdr.customer.account_no }}</td>
                  <td>{{ fdr.customer.customer_name }}</td>
                  <td>{{ fdr.customer.group }}</td>
                  <td>{{ fdr.scheme.scheme_name }}</td>
                  <td>{{ fdr.scheme.scheme_type }}</td>
                  <td>{{ fdr.start_date }}</td>
                  <td>{{ fdr.end_date }}</td>
                  <td>{{ fdr.opening_amount }}</td>
                  <td>{{ fdr.balance_amount }}</td>
                  <td>{{ fdr.monthly_profit_percentage }}</td>
                  <td>{{ fdr.monthly_profit_taka }}</td>
                  <td>{{ fdr.paid_profit }}</td>
                  <td>{{ fdr.available_profit }}</td>
                  <td>{{ fdr.status }}</td>
                  <td><a href="{% url 'fdr_withdraw' fdr.id %}">Withdraw</a></td>
              </tr>
              {% endfor %}
          </tbody>
      </table>
  </div>
</div>
{% endblock %}

templates/app1/fdr/fdr_create.html
{% extends 'base.html' %}
{% load static %}
{% block title %}Add FDR{% endblock %}
{% block style_links %}
<link rel="stylesheet" href="{% static 'app1/customer_details.css' %}">
<link rel="stylesheet" href="{% static 'app1/dps.css' %}">
<link rel="stylesheet" href="https://code.jquery.com/ui/1.13.2/themes/base/jquery-ui.css">
<script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
<script src="https://code.jquery.com/ui/1.13.2/jquery-ui.js"></script>
{% endblock %}

{% block content %}
<h2>Add FDR</h2>
<div class="div1">
    
    <table>
        <tr>
            <th>Account No.</th>
            <td>{{ customer.account_no }}</td>
        </tr>
        <tr>
            <th>Customer Name</th>
            <td>{{ customer.customer_name }}</td>
        </tr>
        <tr>
            <th>Parents</th>
            <td>{{ customer.customer_father }}/{{ customer.customer_mother }}</td>
        </tr>
        <tr>
            <th>Mobile Number</th>
            <td>{{ customer.mobile_number }}</td>
        </tr>
        <tr>
            <th>Customer Type</th>
            <td>{{ customer.customer_type }}</td>
        </tr>
        <tr>
            <th>Somity/Group</th>
            <td>{{ customer.group }}</td>
        </tr>
        <tr>
            <th>Current Address</th>
            <td>{{ customer.current_village }}, {{ customer.current_post_office }}, {{ customer.current_thana }}, {{ customer.current_district }}</td>
        </tr>
        <tr>
            <th>Permanent Address</th>
            <td>{{ customer.permanent_village }}, {{ customer.permanent_post_office }}, {{ customer.permanent_thana }}, {{ customer.permanent_district }}</td>
        </tr>
    </table>
    
    <div class="img-container">
        {% if customer.profile_picture %}
        <div>
            <img src="{{ customer.profile_picture.url }}" class="centered-image">
        </div>
        {% endif %}
    </div>
</div>
<div class="div2">
    <form method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit">Submit</button>
    </form>
</div>
{% endblock %}

{% block scripts %}
<script>
    // Get the input fields
    const openingAmountInput = document.getElementById('id_opening_amount');
    const profitPercentInput = document.getElementById('id_profit_percent');
    const monthlyProfitTakaInput = document.getElementById('id_monthly_profit_taka');

    // Function to calculate and update the monthly profit taka
    function calculateMonthlyProfitTaka() {
        const openingAmount = parseFloat(openingAmountInput.value) || 0;
        const profitPercent = parseFloat(profitPercentInput.value) || 0;
        const monthlyProfitTaka = (openingAmount * profitPercent) / 100;
        monthlyProfitTakaInput.value = monthlyProfitTaka.toFixed(2);
    }

    // Attach event listeners to update the monthly profit taka when inputs change
    openingAmountInput.addEventListener('input', calculateMonthlyProfitTaka);
    profitPercentInput.addEventListener('input', calculateMonthlyProfitTaka);

    // Calculate initially in case values are pre-filled
    calculateMonthlyProfitTaka();
</script>

<script>
    $(function() {
        var today = new Date();
        var formattedDate = $.datepicker.formatDate('yy-mm-dd', today);

        $("#id_start_date").datepicker({
            dateFormat: "yy-mm-dd",
            defaultDate: today,
        }).val(formattedDate);
    });
</script>
{% endblock %}

templates/app1/fdr/fdr_cs_results.html
{% extends 'base.html' %}
{% load static %}
{% block title %}FDR Closing{% endblock %}
{% block style_links %}
<link rel="stylesheet" href="{% static 'app1/customer_details.css' %}">
<link rel="stylesheet" href="{% static 'app1/dps.css' %}">
{% endblock %}

{% block content %}
  <h2>FDR Closing Search Results</h2>

  <div class="div1">
    <table>
        <tr>
            <th>Account No.</th>
            <td>{{ customer.account_no }}</td>
        </tr>
        <tr>
            <th>Customer Name</th>
            <td>{{ customer.customer_name }}</td>
        </tr>
        <tr>
            <th>Parents</th>
            <td>{{ customer.customer_father }}/{{ customer.customer_mother }}</td>
        </tr>
        <tr>
            <th>Mobile Number</th>
            <td>{{ customer.mobile_number }}</td>
        </tr>
        <tr>
            <th>Customer Type</th>
            <td>{{ customer.customer_type }}</td>
        </tr>
        <tr>
            <th>Somity/Group</th>
            <td>{{ customer.group }}</td>
        </tr>
        <tr>
            <th>Current Address</th>
            <td>{{ customer.current_village }}, {{ customer.current_post_office }}, {{ customer.current_thana }}, {{ customer.current_district }}</td>
        </tr>
        <tr>
            <th>Permanent Address</th>
            <td>{{ customer.permanent_village }}, {{ customer.permanent_post_office }}, {{ customer.permanent_thana }}, {{ customer.permanent_district }}</td>
        </tr>
    </table>
    
    <div class="img-container">
        {% if customer.profile_picture %}
        <div>
            <img src="{{ customer.profile_picture.url }}" class="centered-image">
        </div>
        {% endif %}
    </div>
</div>


<div class="div1">
  <div class="table-container">
      <table id="myTable" class="display" style="width:100%">
        <thead>
              <tr>
                  <td>Action</td>
                  <td>Account No</td>
                  <td>Customer Name</td>
                  <td>Somity</td>
                  <td>Scheme</td>
                  <td>Type</td>
                  <td>Start Date</td>
                  <td>End Date</td>
                  <td>Opening Amount</td>
                  <td>Balance</td>
                  <td>Profit %</td>
                  <td>Total Profit</td>
                  <td>Profit Paid</td>
                  <td>Avaailabe Profit</td>
                  <td>Status</td>
              </tr>
          </thead>
          <tbody>
            {% for fdr in fdrs %}
              <tr>
                <td><a href="{% url 'fdr_close' fdr.id %}" onclick="return confirm('Are you sure you want to close?');">Close</a></td>
                  <td>{{ fdr.customer.account_no }}</td>
                  <td>{{ fdr.customer.customer_name }}</td>
                  <td>{{ fdr.customer.group }}</td>
                  <td>{{ fdr.scheme.scheme_name }}</td>
                  <td>{{ fdr.scheme.scheme_type }}</td>
                  <td>{{ fdr.start_date }}</td>
                  <td>{{ fdr.end_date }}</td>
                  <td>{{ fdr.opening_amount }}</td>
                  <td>{{ fdr.balance_amount }}</td>
                  <td>{{ fdr.monthly_profit_percentage }}</td>
                  <td>{{ fdr.monthly_profit_taka }}</td>
                  <td>{{ fdr.paid_profit }}</td>
                  <td>{{ fdr.available_profit }}</td>
                  <td>{{ fdr.status }}</td>
              </tr>
              {% endfor %}
          </tbody>
      </table>
  </div>
</div>


{% endblock %}

templates/app1/fdr/fdr_debit_search.html
{% extends 'base.html' %}
{% load static %}
{% block title %}Search FDR{% endblock %}
{% block style_links %}
<link rel="stylesheet" href="{% static 'app1/add_loan1.css' %}">
{% endblock %}

{% block content %}
<h2>Search FDR</h2>
<div class="div1">
    <form method="post"> {% csrf_token %}

        <div>
            <input type="text" id="account_no" name="account_no" placeholder="Account No." required>
        </div>
        <div>
           <button type="submit">Search</button> 
        </div>
    </form>
    
      {% if error %}
        <p style="color:red;">{{ error }}</p>
      {% endif %}
</div>
{% endblock %}

{% block scripts %}
{% endblock %}

templates/app1/fdr/fdr_deposit_search.html
{% extends 'base.html' %}
{% load static %}
{% block title %}Deposit FDR{% endblock %}
{% block style_links %}
<link rel="stylesheet" href="{% static 'app1/add_loan1.css' %}">
{% endblock %}

{% block content %}
<h2>Deposit FDR</h2>
<div class="div1">
    <form id="form" method="post"> {% csrf_token %}
        <div>
            <input type="text" placeholder="Account No." id="account_no" name="account_no" required> 
        </div>   
        <div>
            <button type="submit">Search</button>
        </div>
    </form>
</div>
{% endblock %}

{% block scripts %}

{% endblock %}

templates/app1/fdr/fdr_search.html
{% extends 'base.html' %}
{% load static %}
{% block title %}FDR Search{% endblock %}
{% block style_links %}
<link rel="stylesheet" href="{% static 'app1/add_loan1.css' %}">
{% endblock %}

{% block content %}
<h2>Add FDR</h2>
<div class="div1">
    <form id="fdrForm" onsubmit="redirectToFDRCreatePage(event)">
        <div>
            <input type="text" placeholder="Account No." id="account_no" name="account_no" required> 
        </div>
        <div>
            <label for="scheme_id">Scheme Name:</label>
            <select id="scheme_id" name="scheme_id" required>
                <option value="">Select Scheme</option>
                {% for scheme in schemes %}
                    <option value="{{ scheme.id }}">{{ scheme.scheme_name }}</option>
                {% endfor %}
            </select>
        </div>
        <div>
            <button type="submit">Search</button>
        </div>
    </form>
</div>
{% endblock %}

{% block scripts %}
<script type="text/javascript">
    function redirectToFDRCreatePage(event) {
        event.preventDefault();
        const accountNo = document.getElementById('account_no').value;
        const schemeId = document.getElementById('scheme_id').value;
        if (accountNo && schemeId) {
            window.location.href = `/fdr-create/${accountNo}/?scheme_id=${schemeId}`;
        }
    }
</script>
{% endblock %}

templates/app1/fdr/fdr_transactions.html
{% extends 'base.html' %}
{% load static %}
{% block title %}Transaction History{% endblock %}
{% block style_links %}
<link rel="stylesheet" href="{% static 'app1/dps.css' %}">
<link rel="stylesheet" href="https://code.jquery.com/ui/1.13.2/themes/base/jquery-ui.css">
{% endblock %}

{% block content %}

<div class="table-container">
    <table id="myTable" class="display" style="width:100%">
        <thead>
            <tr>
                <th>Account No</th>
                <th>Customer Name</th>
                <th>Balance</th>
                <th>Status</th>
            </tr>
        </thead>
        <tbody>
            <tr>
                <td>{{ data.customer.account_no }}</td>
                <td>{{ data.customer.customer_name }}</td>
                <td>{{ data.balance_amount }}</td>
                <td>{{ data.status }}</td>
            </tr>
        </tbody>
    </table>
</div>
  
<h2 style="margin-top: 25px">FDR Transaction History</h2>
<table>
  <thead>
    <tr>
      <th>Date</th>
      <th>Type</th>
      <th>Amount</th>
      <th>Balance</th>
      <th>Note</th>
      <th>Processed By</th>
    </tr>
  </thead>
  <tbody>

    {% for transaction in transactions %}
    <tr>
      <td>{{ transaction.created_at }}</td>
      <td>{{ transaction.get_transaction_type_display }}</td>
      <td>{{ transaction.Amount }}</td>
      <td>{{ transaction.current_balance }}</td>
      <td>{{ transaction.note|default:" " }}</td>
      <td>{{ transaction.processed_by }}</td>
    </tr>
    {% endfor %}
  </tbody>

</table>

{% endblock %}