app1/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.signin, name='login'),
    path('logout/', views.signout, name='logout'),
    path('home/', views.home, name='home'),
    path('customer_home/', views.customer_home, name='customer_home'),
    path('update-active-branch/', views.update_active_branch, name='update_active_branch'),
    path('set_language/', views.set_language, name='set_language'),
    path('customer-login/', views.customer_login, name='customer_login'),
    path('customer-logout/', views.customer_signout, name='customer_logout'),
    path('customer_change_password/', views.customer_change_password, name='customer_change_password'),
    path('access-denied/', views.access_denied, name='access_denied'),

    path('manage-permissions/', views.manage_permissions, name='manage_permissions'),

    path('customers-add/', views.customer_add, name='customer_add'),
    path('customers-list/', views.customer_list, name='customer_list'),
    path('customers-details/<int:id>/', views.customer_details, name='customer_details'),
    path('customers-edit/<int:id>/', views.customer_edit, name='customer_edit'),

    path('general-list/', views.general_list, name='general_list'),
    path('general-deposit/<int:id>/', views.general_deposit, name='general_deposit'),
    path('general-withdraw/<int:id>/', views.general_withdraw, name='general_withdraw'),
    path('general-transactions/<int:id>/', views.general_transaction_history, name='general_transaction_history'),
    path('general-deposit-search/', views.general_deposit_search, name='general_deposit_search'),
    path('general-withdraw-search/', views.general_withdraw_search, name='general_withdraw_search'),

    path('savings-list/', views.savings_list, name='savings_list'),
    path('savings-deposit/<int:id>/', views.savings_deposit, name='savings_deposit'),
    path('savings-withdraw/<int:id>/', views.savings_withdraw, name='savings_withdraw'),
    path('savings-transactions/<int:id>/', views.savings_transaction_history, name='savings_transaction_history'),
    path('savings-deposit-search/', views.savings_deposit_search, name='savings_deposit_search'),
    path('savings-withdraw-search/', views.savings_withdraw_search, name='savings_withdraw_search'),

    path('loan-search/', views.loan_search, name='loan_search'),
    path('loan-list/', views.loan_list, name='loan_list'),
    path('loan-create/<str:account_no>/', views.loan_create, name='loan_create'),
    path('loan-schedule/<int:loan_id>/', views.loan_schedule, name='loan_schedule'),
    path('loan-collection/<int:loan_id>/', views.loan_collection, name='loan_collection'),
    path('loan-transaction/<int:loan_id>/', views.loan_trans, name='loan_trans'),
    path('loan-fine/<int:loan_id>/', views.loan_fine, name='loan_fine'),
    path('loan-collection-search/', views.loan_collection_search, name='loan_collection_search'),
    path('loan-close-search/', views.loan_close_search, name='loan_close_search'),
    path('loan-close/<int:loan_id>/', views.loan_close, name='loan_close'),



    path('loan-cc-search/', views.loan_cc_search, name='loan_cc_search'),
    path('loan-cc-list/', views.loan_cc_list, name='loan_cc_list'),
    path('loan-cc-create/<str:account_no>/', views.loan_cc_create, name='loan_cc_create'),
    path('loan-cc-collection/<int:loan_id>/', views.loan_cc_collection, name='loan_cc_collection'),
    path('loan-cc-transaction/<int:loan_id>/', views.loan_cc_trans, name='loan_cc_trans'),
    path('loan-cc-collection-search/', views.loan_cc_collection_search, name='loan_cc_collection_search'),
    path('loan-cc-close-search/', views.loan_cc_close_search, name='loan_cc_close_search'),
    path('loan-cc-close/<int:loan_id>/', views.loan_cc_close, name='loan_cc_close'),


    path('loan-special-search/', views.loan_sp_search, name='loan_sp_search'),
    path('loan-special-list/', views.loan_sp_list, name='loan_sp_list'),
    path('loan-special-create/<str:account_no>/', views.loan_sp_create, name='loan_sp_create'),
    path('loan-special-collection/<int:loan_id>/', views.loan_sp_collection, name='loan_sp_collection'),
    path('loan-special-close-search/', views.loan_sp_close_search, name='loan_sp_close_search'),
    path('loan-special-close/<int:loan_id>/', views.loan_sp_close, name='loan_sp_close'),



    path('dps-search/', views.dps_search, name='dps_search'),
    path('dps-list/', views.dps_list, name='dps_list'),
    path('dps-create/<str:account_no>/', views.dps_create, name='dps_create'),
    path('dps-schedule/<int:id>/', views.dps_schedule, name='dps_schedule'),
    path('dps-deposit/<int:id>/', views.dps_deposit, name='dps_deposit'),
    path('dps-withdraw/<int:id>/', views.dps_withdraw, name='dps_withdraw'),
    path('dps-transaction/<int:id>/', views.dps_transaction, name='dps_transaction'),
    path('dps-deposit-search/', views.dps_deposit_search, name='dps_deposit_search'),
    path('dps-withdraw-search/', views.dps_withdraw_search, name='dps_withdraw_search'),
    path('dps-close-search/', views.dps_close_search, name='dps_close_search'),
    path('dps-close/<int:id>/', views.dps_close, name='dps_close'),

    path('fdr-search/', views.fdr_search, name='fdr_search'),
    path('fdr-list/', views.fdr_list, name='fdr_list'),
    path('fdr-create/<str:account_no>/', views.fdr_create, name='fdr_create'),
    path('fdr-deposit/<int:id>/', views.fdr_deposit, name='fdr_deposit'),
    path('fdr-withdraw/<int:id>/', views.fdr_withdraw, name='fdr_withdraw'),
    path('fdr-profit-withdraw/<int:id>/', views.fdr_profit_withdraw, name='fdr_profit_withdraw'),
    path('fdr-transactions/<int:id>/', views.fdr_transaction_history, name='fdr_transaction_history'),
    path('fdr-profit/<int:id>/', views.fdr_profit, name='fdr_profit'),
    path('fdr-deposit-search/', views.fdr_deposit_search, name='fdr_deposit_search'),
    path('fdr-profit-withdraw-search/', views.fdr_profit_withdraw_search, name='fdr_profit_withdraw_search'),
    path('fdr-balance-withdraw-search/', views.fdr_balance_withdraw_search, name='fdr_balance_withdraw_search'),
    path('fdr-close-search/', views.fdr_close_search, name='fdr_close_search'),
    path('fdr-close/<int:id>/', views.fdr_close, name='fdr_close'),

    path('share-list/', views.share_list, name='share_list'),
    path('share-create/<str:account_no>/', views.share_create, name='share_create'),
    path('share-search/', views.share_search, name='share_search'),
    path('share-deposit/<int:share_id>/', views.share_deposit, name='share_deposit'),
    path('share-deposit-search/', views.share_deposit_search, name='share_deposit_search'),
    path('share-withdraw-search/', views.share_withdraw_search, name='share_withdraw_search'),
    path('share-profit-withdraw-search/', views.share_profit_withdraw_search, name='share_profit_withdraw_search'),
    path('share-withdraw/<int:share_id>/', views.share_withdraw, name='share_withdraw'),
    path('share-transfer/<int:share_id>/', views.share_transfer, name='share_transfer'),
    path('share-profit-withdraw/<int:share_id>/', views.share_profit_withdraw, name='share_profit_withdraw'),
    path('share-transaction-history/<int:share_id>/', views.share_transaction_history, name='share_transaction_history'),

    path('bank_withdraw/', views.bank_withdraw, name='bank_withdraw'),
    path('bank_deposit/', views.bank_deposit, name='bank_deposit'),
    path('package/', views.package, name='package'),

    path('delete-search/', views.delete_search, name='delete_search'),
    path('delete-customer/<int:id>/', views.delete_customer, name='delete_customer'),
    path('delete-loan/<int:id>/', views.loan_delete, name='loan_delete'),
    path('delete-loan-cc/<int:id>/', views.loan_cc_delete, name='loan_cc_delete'),
    path('delete-loan-sp/<int:id>/', views.loan_sp_delete, name='loan_sp_delete'),
    path('delete-dps/<int:id>/', views.dps_delete, name='dps_delete'),
    path('delete-fdr/<int:id>/', views.fdr_delete, name='fdr_delete'),
    path('delete-share/<int:share_id>/', views.share_delete, name='share_delete'),

    path('somity_wise_dps_deposit/', views.somity_wise_dps_deposit, name='somity_wise_dps_deposit'),
    path('somity_wise_general_deposit/', views.somity_wise_general_deposit, name='somity_wise_general_deposit'),
    path('somity_wise_loan/', views.somity_wise_loan, name='somity_wise_loan'),
    path('common_collection/', views.common_collection, name='common_collection'),
]

project/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('app1.urls')),
    path('', include('primary_setup.urls')),
    path('', include('otrans.urls')),
    path('report/', include('report.urls')),
    path('sheet/', include('sheet.urls')),
    path('dashboard/', include('dashboard.urls')),
    path('sms/', include('sms.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

sms/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('sms_single/', views.sms_single, name='sms_single'),
    path('sms_bulk/', views.sms_bulk, name='sms_bulk'),
    path('sms_customer/', views.sms_customer, name='sms_customer'),
    path('sms_report/', views.sms_report, name='sms_report'),
]

sms/models.py
from django.db import models

class SMSReport(models.Model):
    date = models.DateTimeField(auto_now_add=True)
    sms_type = models.CharField(max_length=50)  # Type of the SMS, e.g., 'All Customer'
    mobile_number = models.CharField(max_length=15)
    sms_body = models.TextField()
    sent_by = models.CharField(max_length=150)  # Store the username of the user who sent the SMS

    def __str__(self):
        return f"SMS to {self.mobile_number} on {self.date}"

templates/app1/bank_deposit.html
{% extends 'base.html' %}
{% load i18n %}
{% load static %}
{% block title %}{% trans "Bank Deposit" %}{% endblock %}
{% block style_links %}
<link rel="stylesheet" href="{% static 'app1/dps.css' %}">
<link rel="stylesheet" href="https://code.jquery.com/ui/1.13.2/themes/base/jquery-ui.css">
<script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
<script src="https://code.jquery.com/ui/1.13.2/jquery-ui.js"></script>
{% endblock %}

{% block content %}
<h1>{% trans "Bank Deposit" %}</h1>

<div class="div2">
<form method="post" enctype="multipart/form-data">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit" class="btn btn-primary">{% trans "Submit" %}</button>
</form>
</div>

<h2>{% trans "Transaction History" %}</h2>
<div class="table-container">
<table class="table">
    <thead>
        <tr>
            {% comment %} <th>Date</th> {% endcomment %}
            <th>{% trans "Bank" %}</th>
            <th>{% trans "Deposit Amount" %}</th>
            <th>{% trans "Withdraw Amount" %}</th>
            <th>{% trans "Balance" %}</th>
            <th>{% trans "Note" %}</th>
            <th>{% trans "Attachment" %}</th>
            <th>{% trans "Process By" %}</th>
            <th>{% trans "Entry Date" %}</th>
        </tr>
    </thead>
    <tbody>
        {% for transaction in bank_transactions %}
        <tr>
            {% comment %} <td>{{ transaction.date }}</td> {% endcomment %}
            <td>{{ transaction.bank.bank_name }}</td>
            <td>{{ transaction.deposit_amount }}</td>
            <td>{{ transaction.withdraw_amount }}</td>
            <td>{{ transaction.bank.balance }}</td>
            <td>{{ transaction.note|default:"" }}</td>
            <td>
                {% if transaction.attachment %}
                <a href="{{ transaction.attachment.url }}">{% trans "Download" %}</a>
                {% else %}
                -
                {% endif %}
            </td>
            <td>{{ transaction.processed_by }}</td>
            <td>{{ transaction.entry_date }}</td>
        </tr>
        {% endfor %}
    </tbody>
</table>
</div>
{% endblock %}

{% block scripts %}
<script>
    $(function() {
        var today = new Date();
        var formattedDate = $.datepicker.formatDate('yy-mm-dd', today);

        $("#id_date").datepicker({
            dateFormat: "yy-mm-dd",
            defaultDate: today,
        }).val(formattedDate);
    });
</script>
{% endblock %}

templates/app1/bank_withdraw.html
{% extends 'base.html' %}
{% load i18n %}
{% load static %}
{% block title %}Bank Withdraw{% endblock %}
{% block style_links %}
<link rel="stylesheet" href="{% static 'app1/dps.css' %}">
<link rel="stylesheet" href="https://code.jquery.com/ui/1.13.2/themes/base/jquery-ui.css">
<script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
<script src="https://code.jquery.com/ui/1.13.2/jquery-ui.js"></script>
{% endblock %}

{% block content %}
<h1>Bank Withdraw</h1>

<div class="div2">
<form method="post" enctype="multipart/form-data">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit" class="btn btn-primary">Submit</button>
</form>
</div>

<h2>Transaction History</h2>
<div class="table-container">
<table class="table">
    <thead>
        <tr>
            {% comment %} <th>Date</th> {% endcomment %}
            <th>Bank</th>
            <th>Deposit Amount</th>
            <th>Withdraw Amount</th>
            <th>Balance</th>
            <th>Note</th>
            <th>Attachment</th>
            <th>Process By</th>
            <th>Entry Date</th>
        </tr>
    </thead>
    <tbody>
        {% for transaction in bank_transactions %}
        <tr>
            {% comment %} <td>{{ transaction.date }}</td> {% endcomment %}
            <td>{{ transaction.bank.bank_name }}</td>
            <td>{{ transaction.deposit_amount }}</td>
            <td>{{ transaction.withdraw_amount }}</td>
            <td>{{ transaction.bank.balance }}</td>
            <td>{{ transaction.note }}</td>
            <td>
                {% if transaction.attachment %}
                <a href="{{ transaction.attachment.url }}">Download</a>
                {% else %}
                -
                {% endif %}
            </td>
            <td>{{ transaction.processed_by }}</td>
            <td>{{ transaction.entry_date }}</td>
        </tr>
        {% endfor %}
    </tbody>
</table>
</div>
{% endblock %}

{% block scripts %}
<script>
    $(function() {
        var today = new Date();
        var formattedDate = $.datepicker.formatDate('yy-mm-dd', today);

        $("#id_date").datepicker({
            dateFormat: "yy-mm-dd",
            defaultDate: today,
        }).val(formattedDate);
    });
</script>
{% endblock %}

templates/app1/customer_login.html
<!DOCTYPE html>
<html lang="en">
<head>
    {% load static %}
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="author" content="soash">
    <meta name="author" content="Soash Sadat">
    <!-- Developed by Soash Sadat -->
    <!-- https://soash.github.io/ -->
    <link rel="icon" type="image/x-icon" href="{% static 'favicon.ico' %}">
    <title>Login</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/css/bootstrap.min.css" rel="stylesheet">
    <style>
        body{
            background: #ddd;
            display: flex;
            justify-content: center;
            align-items: center;
            height: 100vh;
        }
    </style>
</head>
<body>




    <div class="container">
        <div class="row">
            <div class="col-12 col-md-6 mx-auto bg-white p-4" style="border-radius: 20px;">


                {% if logo %}
                    <div class="d-flex justify-content-center mb-4">
                        <img src="{{ logo.image.url }}" alt="Site Logo" class="w-50">
                    </div>
                {% else %}
                     <!-- Fallback logo -->
                    <div class="d-flex justify-content-center mb-4">
                        <img src="{% static 'img/logo.jpg' %}" class="w-50">
                    </div>
                {% endif %}
                
                <h2 class="mb-4 text-center">Customer Login</h2>
                <form method="post" class="mt-4" action="{% url 'customer_login' %}">
                    {% csrf_token %}
                    <div class="mb-3">
                        <label for="username" class="form-label">Account Number:</label>
                        <input type="text" class="form-control" name="username" id="username" required>
                    </div>
                    <div class="mb-3">
                        <label for="password" class="form-label">Password:</label>
                        <input type="password" class="form-control" name="password" id="password" required>
                    </div>
                    <div class="d-flex justify-content-center mb-3">
                        <button type="submit" class="btn btn-primary w-50">Login</button>
                    </div>
                    <div class="text-end">
                        <a href="{% url 'login' %}" class="text-danger text-decoration-none">Admin Login</a>
                    </div>
                </form>
            </div>        
        </div>
        <div class="row">
            <div class="bg-primary text-center mt-3 text-white p-2 rounded mx-auto col-12 col-md-6">
                <span>Powered By <b>সমিতি হিসাব - Samity Hisab</b></span>
            </div>
        </div>
        
        {% if messages %}
            <ul class="mt-3">
                {% for message in messages %}
                    <div class="alert alert-danger">{{ message }}</div>
                {% endfor %}
            </ul>
        {% endif %}
    </div>

    <!-- Bootstrap JS (optional) -->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/js/bootstrap.bundle.min.js"></script>
</body>
</html>

templates/app1/delete_search.html
{% extends 'base.html' %}
{% load i18n %}
{% load static %}
{% block title %}{% trans "Delete" %}{% endblock %}
{% block style_links %}
<link rel="stylesheet" href="{% static 'app1/add_loan1.css' %}">
{% endblock %}

{% block content %}
<h2>{% trans "Delete" %}</h2>
<div class="div1">
    <form id="form" method="post"> {% csrf_token %}
        <div>
            <input type="text" placeholder="{% trans 'Account No.' %}" id="account_no" name="account_no" required> 
        </div>   
        <div>
            <button type="submit">{% trans "Search" %}</button>
        </div>
    </form>
</div>
{% endblock %}

{% block scripts %}

{% endblock %}

templates/app1/delete_search_results.html
{% extends 'base.html' %}
{% load i18n %}
{% load static %}
{% block title %}{% trans "Delete" %}{% endblock %}
{% block style_links %}
<link rel="stylesheet" href="{% static 'app1/customer_details.css' %}">
<link rel="stylesheet" href="{% static 'app1/dps.css' %}">
<style>
    .div3{
        flex-direction: column;
    }
    h2{
        margin: 0;
        padding: 0;
    }
    .main table{
        margin-top: 0;
    }
</style>
{% endblock %}

{% block content %}
<div class="div1">
    <table>
        <tr>
            <th>{% trans "Account No." %}</th>
            <td>{{ customer.account_no }}</td>
        </tr>
        <tr>
            <th>{% trans "Customer Name" %}</th>
            <td>{{ customer.customer_name }}</td>
        </tr>
        <tr>
            <th>{% trans "Parents" %}</th>
            <td>{{ customer.customer_father }}/{{ customer.customer_mother }}</td>
        </tr>
        <tr>
            <th>{% trans "Mobile Number" %}</th>
            <td>{{ customer.mobile_number }}</td>
        </tr>
        <tr>
            <th>{% trans "Customer Type" %}</th>
            <td>{{ customer.customer_type }}</td>
        </tr>
        <tr>
            <th>{% trans "Somity/Group" %}</th>
            <td>{{ customer.group }}</td>
        </tr>
        <tr>
            <th>{% trans "Current Address" %}</th>
            <td>{{ customer.current_village }}, {{ customer.current_post_office }}, {{ customer.current_thana }}, {{ customer.current_district }}</td>
        </tr>
        <tr>
            <th>{% trans "Permanent Address" %}</th>
            <td>{{ customer.permanent_village }}, {{ customer.permanent_post_office }}, {{ customer.permanent_thana }}, {{ customer.permanent_district }}</td>
        </tr>
    </table>
    
    <div class="img-container">
        {% if customer.profile_picture %}
        <div>
            <img src="{{ customer.profile_picture.url }}" class="centered-image">
        </div>
        {% endif %}
    </div>
</div>


<div class="div1 div3">
    <h2>{% trans "FDR" %}</h2>
  <div class="table-container">
      <table id="myTable" class="display" style="width:100%">
        <thead>
              <tr>
                  <td>{% trans "Action" %}</td>
                  <td>{% trans "Account No" %}</td>
                  <td>{% trans "Customer Name" %}</td>
                  <td>{% trans "Somity" %}</td>
                  <td>{% trans "Scheme" %}</td>
                  <td>{% trans "Type" %}</td>
                  <td>{% trans "Start Date" %}</td>
                  <td>{% trans "End Date" %}</td>
                  <td>{% trans "Opening Amount" %}</td>
                  <td>{% trans "Balance" %}</td>
                  <td>{% trans "Profit" %} %</td>
                  <td>{% trans "Total Profit" %}</td>
                  <td>{% trans "Profit Paid" %}</td>
                  <td>{% trans "Available Profit" %}</td>
                  <td>{% trans "Status" %}</td>
              </tr>
          </thead>
          <tbody>
            {% for fdr in fdrs %}
              <tr>
                <td><a href="{% url 'fdr_close' fdr.id %}" onclick="return confirm('{% trans "Are you sure you want to close?" %}');">{% trans "Close" %}</a></td>
                  <td>{{ fdr.customer.account_no }}</td>
                  <td>{{ fdr.customer.customer_name }}</td>
                  <td>{{ fdr.customer.group }}</td>
                  <td>{{ fdr.scheme.scheme_name }}</td>
                  <td>{{ fdr.scheme.scheme_type }}</td>
                  <td>{{ fdr.start_date }}</td>
                  <td>{{ fdr.end_date }}</td>
                  <td>{{ fdr.opening_amount }}</td>
                  <td>{{ fdr.balance_amount }}</td>
                  <td>{{ fdr.monthly_profit_percentage }}</td>
                  <td>{{ fdr.monthly_profit_taka }}</td>
                  <td>{{ fdr.paid_profit }}</td>
                  <td>{{ fdr.available_profit }}</td>
                  <td>{{ fdr.status }}</td>
              </tr>
              {% endfor %}
          </tbody>
      </table>
  </div>
</div>

{% endblock %}

templates/app1/deny.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <h1>Access Denied</h1>
    <p>You do not have permission to access this page.</p>

</body>
</html>

templates/app1/login.html
<!DOCTYPE html>
<html lang="en">
<head>
    {% load static %}
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="author" content="Soash Sadat">
    <!-- Developed by Soash Sadat -->
    <!-- https://soash.github.io/ -->
    <link rel="icon" type="image/x-icon" href="{% static 'favicon.ico' %}">
    <title>Login</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/css/bootstrap.min.css" rel="stylesheet">
    <style>
        body{
            background: #ddd;
            display: flex;
            justify-content: center;
            align-items: center;
            height: 100vh;
        }
    </style>
</head>
<body>

    <div class="container">
        <div class="row">
            <div class="col-12 col-md-6 mx-auto bg-white p-4" style="border-radius: 20px;">

                {% if logo %}
                    <div class="d-flex justify-content-center mb-4">
                        <img src="{{ logo.image.url }}" alt="Site Logo" class="w-50">
                    </div>
                {% else %}
                     <!-- Fallback logo -->
                    <div class="d-flex justify-content-center mb-4">
                        <img src="{% static 'img/logo.jpg' %}" class="w-50">
                    </div>
                {% endif %}
                
                <h2 class="mb-4 text-center">Login to your account</h2>
                <form method="post">
                    {% csrf_token %}
                    <div class="mb-3">
                        <label for="username" class="form-label">Username:</label>
                        <input type="text" class="form-control" name="username" id="username" required>
                    </div>
                    <div class="mb-3">
                        <label for="password" class="form-label">Password:</label>
                        <input type="password" class="form-control" name="password" id="password" required>
                    </div>
                    <div class="d-flex justify-content-center mb-3">
                        <button type="submit" class="btn btn-primary w-50">Login</button>
                    </div>
                    <div class="text-end">
                        <a href="{% url 'customer_login' %}" class="text-danger text-decoration-none">Member Login</a>
                    </div>
                </form>
            </div>        
        </div>
        <div class="row">
            <div class="bg-primary text-center mt-3 text-white p-2 rounded mx-auto col-12 col-md-6">
                <span>Powered By <b>সমিতি হিসাব - Samity Hisab</b></span>
            </div>
        </div>
        <div class="row">
            <div class="bg-success text-center mt-3 text-white p-2 rounded mx-auto col-12 col-md-6">
                <span>Developed By <b><a href="https://soash.github.io/" class="text-white text-decoration-none" target="_blank">Soash Sadat</a></b></span>
            </div>
        </div>
        
        
        {% if messages %}
            <ul class="mt-3">
                {% for message in messages %}
                    <div class="alert alert-danger">{{ message }}</div>
                {% endfor %}
            </ul>
        {% endif %}
    </div>

    <!-- Bootstrap JS (optional) -->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/js/bootstrap.bundle.min.js"></script>
</body>
</html>

templates/app1/package.html
{% extends 'base.html' %}
{% load i18n %}
{% load static %}
{% block title %}{% trans "Package Details" %}{% endblock %}
{% block style_links %}
<link rel="stylesheet" href="{% static 'app1/customer_details.css' %}">
<style>

</style>
{% endblock %}

{% block content %}
<h2>{% trans "Package Details" %}</h2>
<div class="div1">
    
    {% if package %}
    <table>
        <tr>
            <th>{% trans "Client ID" %}</th>
            <td>: {{ package.client_id }}</td>
        </tr>
        <tr>
            <th>{% trans "Status" %}</th>
            <td>: {{ package.status }}</td>
        </tr>
        <tr>
            <th>{% trans "Start Date" %}</th>
            <td>: {{ package.start_date|date:"d-M-Y" }}</td>
        </tr>
        <tr>
            <th>{% trans "Expired Date" %}</th>
            <td>: {{ package.expired_date|date:"d-M-Y" }}</td>
        </tr>
        <tr>
            <th>{% trans "Billing Cycle" %}</th>
            <td>: {{ package.billing_cycle }}</td>
        </tr>
        <tr>
            <th>{% trans "Package Name" %}</th>
            <td>: {{ package.package_name }}</td>
        </tr>
        <tr>
            <th>{% trans "Limit Customer" %}</th>
            <td>: {{ package.limit_customer }}</td>
        </tr>
    </table>
    {% else %}
        <p>{% trans "No package data available" %}</p>
    {% endif %}

</div>
{% endblock %}

{% block scripts %}

{% endblock %}