project/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('app1.urls')),
    path('', include('primary_setup.urls')),
    path('', include('otrans.urls')),
    path('report/', include('report.urls')),
    path('sheet/', include('sheet.urls')),
    path('dashboard/', include('dashboard.urls')),
    path('sms/', include('sms.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

report/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('daily-loan-report/', views.daily_loan_report, name='daily_loan_report'),
    path('weekly-loan-report/', views.weekly_loan_report, name='weekly_loan_report'),
    path('monthly-loan-report/', views.monthly_loan_report, name='monthly_loan_report'),
    path('report/loan-due-list/', views.loan_due_list, name='loan_due_list'),
    path('report/loan-recovery-percentage/', views.loan_recovery_percentage, name='loan_recovery_percentage'),
    path('customer-report', views.customer_report, name='customer_report'),
    path('customer-balance', views.customer_balance, name='customer_balance'),
    path('bank-transactions', views.bank_transactions, name='bank_transactions'),

    path('monthly_top_sheet_report/', views.monthly_top_sheet_report, name='monthly_top_sheet_report'),
    path('monthly_wise_top_sheet_report/', views.monthly_wise_top_sheet_report, name='monthly_wise_top_sheet_report'),

    path('fixed_deposit_report/', views.fixed_deposit_report, name='fixed_deposit_report'),
    path('dps_report/', views.dps_report, name='dps_report'),
    path('share_report/', views.share_report, name='share_report'),
    path('voucher_report/', views.voucher_report, name='voucher_report'),
    path('loanOC_report/', views.loanOC_report, name='loanOC_report'),
    path('balance_sheet/', views.balance_sheet, name='balance_sheet'),
    path('user_log/', views.user_log, name='user_log'),
    path('user_entry_summary/', views.user_entry_summary, name='user_entry_summary'),
    path('user_wise_entry_summary/', views.user_wise_entry_summary, name='user_wise_entry_summary'),
    path('general_ledger/', views.general_ledger, name='general_ledger'),
    path('ReceivePayment/', views.ReceivePayment, name='ReceivePayment'),
    path('ProfitLoss/', views.ProfitLoss, name='ProfitLoss'),
    path('account_statement/', views.account_statement, name='account_statement'),
]

sms/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('sms_single/', views.sms_single, name='sms_single'),
    path('sms_bulk/', views.sms_bulk, name='sms_bulk'),
    path('sms_customer/', views.sms_customer, name='sms_customer'),
    path('sms_report/', views.sms_report, name='sms_report'),
]

report/models.py
from django.db import models
from django.utils import timezone
from primary_setup.models import Branch, CustomUser
from app1.models import ActiveBranch, Customer
import socket
from django.db.models import Sum

def get_ip_address():
    try:
        s = socket.socket(socket.AF_INET, socket.SOCK_DGRAM)
        s.connect(("8.8.8.8", 80))
        ip_address = s.getsockname()[0]
        s.close()
        return ip_address
    except Exception as e:
        return str(e)



class UserLog(models.Model):
    TRANSACTION_TYPE_CHOICES = [
        ('cash_in', 'Cash In'),
        ('cash_out', 'Cash Out'),
    ]
    CASHFLOW1_TYPE_CHOICES = [
        ('income', 'Income'),
        ('expense', 'Expense'),
    ]
    CASHFLOW2_TYPE_CHOICES = [
        ('receive', 'Receive'),
        ('payment', 'Payment'),
    ]

    branch = models.ForeignKey(Branch, on_delete=models.CASCADE, null=True, blank=True)
    customer = models.ForeignKey(Customer, on_delete=models.CASCADE, null=True, blank=True)
    processed_by = models.ForeignKey(CustomUser, on_delete=models.SET_NULL, null=True, blank=True)
    action = models.CharField(max_length=300, null=True, blank=True)
    logs_action = models.CharField(max_length=300, null=True, blank=True)

    transaction_type = models.CharField(max_length=10, choices=TRANSACTION_TYPE_CHOICES, null=True, blank=True)
    cashflow_type1 = models.CharField(max_length=10, choices=CASHFLOW1_TYPE_CHOICES, null=True, blank=True)
    cashflow_type2 = models.CharField(max_length=10, choices=CASHFLOW2_TYPE_CHOICES, null=True, blank=True)

    amount = models.DecimalField(max_digits=10, decimal_places=2, null=True, blank=True)
    # timestamp = models.DateTimeField(default=timezone.now)
    timestamp = models.DateTimeField(auto_now=True)
    ip_address = models.CharField(max_length=300, null=True, blank=True)
    description = models.CharField(max_length=300, null=True, blank=True)

    trx = models.BooleanField(null=True, blank=True)

    def save(self, *args, **kwargs):
        if not self.ip_address:
            self.ip_address = get_ip_address()
        if not self.branch and self.action not in [1, 2]:
            active_branch = ActiveBranch.objects.filter(user=self.processed_by).first()
            if active_branch:
                self.branch = active_branch.branch
            else:
                active_branch = None
                self.branch = active_branch
            
        if not self.logs_action:
            if not self.transaction_type and not self.cashflow_type1 and not self.cashflow_type2:
                self.transaction_type = 'cash_in'
                self.cashflow_type1 = 'income'
                self.cashflow_type2 = 'receive'
            if self.trx:
                self.transaction_type = 'cash_out'
                self.cashflow_type1 = 'expense'
                self.cashflow_type2 = 'payment'
        
        super().save(*args, **kwargs)

    def __str__(self):
        return f"{self.processed_by.username if self.processed_by else 'Unknown'} - {self.transaction_type} at {self.timestamp}"
    
    @staticmethod
    def get_sum_of_amounts_by_action():
        """
        Returns a dictionary with the sum of amounts for each unique action.
        """
        return UserLog.objects.values('action').annotate(total_amount=Sum('amount')).order_by('action')

report/forms.py
from django import forms
from primary_setup.models import CustomUser, DPSScheme, LoanCategory, Somity, FDRScheme, VoucherCategory
from app1.models import ActiveBranch
from report.models import UserLog

class GroupSelectionForm(forms.Form):
    group = forms.ModelMultipleChoiceField(
        queryset=Somity.objects.none(),
        widget=forms.CheckboxSelectMultiple,
        required=True,
    )

    def __init__(self, *args, **kwargs):
        branch = kwargs.pop('branch', None)
        super().__init__(*args, **kwargs)
        if branch:
            self.fields['group'].queryset = Somity.objects.filter(branch=branch)

class GroupSchemeSelectionForm(forms.Form):
    group = forms.ModelMultipleChoiceField(
        queryset=Somity.objects.none(), 
        widget=forms.CheckboxSelectMultiple,
        label="Select Somity/Group"
    )
    scheme = forms.ChoiceField(
        choices=[
            ('daily', 'Daily'),
            ('weekly', 'Weekly'),
            ('half_monthly', 'Half Monthly'),
            ('monthly', 'Monthly')
        ],
        label="Select Loan Scheme"
    )

    def __init__(self, *args, **kwargs):
        branch = kwargs.pop('branch', None)
        super(GroupSchemeSelectionForm, self).__init__(*args, **kwargs)
        if branch:
            self.fields['group'].queryset = Somity.objects.filter(branch=branch)



class CustomerSearchForm(forms.Form):
    start_date = forms.DateField(label='Start Date', widget=forms.DateInput(attrs={'type': 'date'}))
    end_date = forms.DateField(label='End Date', widget=forms.DateInput(attrs={'type': 'date'}))
    somity = forms.ModelMultipleChoiceField(
        queryset=Somity.objects.none(),
        widget=forms.CheckboxSelectMultiple,
        required=True,
    )

    def __init__(self, *args, **kwargs):
        branch = kwargs.pop('branch', None)
        super().__init__(*args, **kwargs)
        if branch:
            self.fields['somity'].queryset = Somity.objects.filter(branch=branch)



class FixedDepositReportForm(forms.Form):
    somity = forms.ModelMultipleChoiceField(
        queryset=Somity.objects.none(),
        widget=forms.SelectMultiple(attrs={'class': 'form-control'}),
        required=True,
    )
    start_date = forms.DateField(
        widget=forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'Date From'}),
        required=False
    )
    end_date = forms.DateField(
        widget=forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'Date To'}),
        required=False
    )
    scheme_name = forms.ModelChoiceField(
        queryset=FDRScheme.objects.none(),
        widget=forms.Select(attrs={'class': 'form-control'}),
        required=False
    )
    status = forms.ChoiceField(
        choices=[('all', 'All'), ('active', 'Active'), ('closed', 'Closed')],
        widget=forms.Select(attrs={'class': 'form-control'}),
        required=False
    )
    account_number = forms.CharField(
        widget=forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'Account No.'}),
        required=False
    )

    def __init__(self, *args, **kwargs):
        user = kwargs.pop('user', None)
        super(FixedDepositReportForm, self).__init__(*args, **kwargs)
        
        if user:
            active_branch = ActiveBranch.objects.get(user=user).branch
            self.fields['somity'].queryset = Somity.objects.filter(branch=active_branch)
            self.fields['scheme_name'].queryset = FDRScheme.objects.filter(branch=active_branch)


class DPSReportForm(forms.Form):
    somity = forms.ModelMultipleChoiceField(
        queryset=Somity.objects.none(),
        widget=forms.SelectMultiple(attrs={'class': 'form-control'}),
        required=True,
    )
    start_date = forms.DateField(
        widget=forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'Date From'}),
        required=False
    )
    end_date = forms.DateField(
        widget=forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'Date To'}),
        required=False
    )
    scheme_name = forms.ModelChoiceField(
        queryset=DPSScheme.objects.none(),
        widget=forms.Select(attrs={'class': 'form-control'}),
        required=False
    )
    status = forms.ChoiceField(
        choices=[('all', 'All'), ('active', 'Active'), ('closed', 'Closed')],
        widget=forms.Select(attrs={'class': 'form-control'}),
        required=False
    )
    account_number = forms.CharField(
        widget=forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'Account No.'}),
        required=False
    )

    def __init__(self, *args, **kwargs):
        user = kwargs.pop('user', None)
        super(DPSReportForm, self).__init__(*args, **kwargs)
        
        if user:
            active_branch = ActiveBranch.objects.get(user=user).branch
            self.fields['somity'].queryset = Somity.objects.filter(branch=active_branch)
            self.fields['scheme_name'].queryset = DPSScheme.objects.filter(branch=active_branch)


class ShareReportForm(forms.Form):
    somity = forms.ModelMultipleChoiceField(
        queryset=Somity.objects.none(),
        widget=forms.SelectMultiple(attrs={'class': 'form-control'}),
        required=True,
    )
    start_date = forms.DateField(
        widget=forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'Date From'}),
        required=False
    )
    end_date = forms.DateField(
        widget=forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'Date To'}),
        required=False
    )
    account_number = forms.CharField(
        widget=forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'Account No.'}),
        required=False
    )

    def __init__(self, *args, **kwargs):
        user = kwargs.pop('user', None)
        super(ShareReportForm, self).__init__(*args, **kwargs)
        
        if user:
            active_branch = ActiveBranch.objects.get(user=user).branch
            self.fields['somity'].queryset = Somity.objects.filter(branch=active_branch)


class VoucherReportForm(forms.Form):
    start_date = forms.DateField(
        widget=forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'Date From'}),
        required=True
    )
    end_date = forms.DateField(
        widget=forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'Date To'}),
        required=True
    )
    status = forms.ChoiceField(
        choices=[('Income', 'Income'), ('Expense', 'Expense')],
        widget=forms.Select(attrs={'class': 'form-control'}),
        required=True
    )
    voucher_category = forms.ModelChoiceField(
        queryset=VoucherCategory.objects.none(),
        widget=forms.Select(attrs={'class': 'form-control'}),
        required=False,
    )
    # user = forms.ModelChoiceField(
    #     queryset=CustomUser.objects.none(),
    #     widget=forms.Select(attrs={'class': 'form-control'}),
    #     required=False,
    # )

    def __init__(self, *args, **kwargs):
        user = kwargs.pop('user', None)
        super(VoucherReportForm, self).__init__(*args, **kwargs)
        
        if user:
            active_branch = ActiveBranch.objects.get(user=user).branch
            self.fields['voucher_category'].queryset = VoucherCategory.objects.filter(branch=active_branch)
            # self.fields['user'].queryset = CustomUser.objects.filter(branch=active_branch)



class LoanOCReportForm(forms.Form):
    somity = forms.ModelMultipleChoiceField(
        queryset=Somity.objects.none(),
        widget=forms.SelectMultiple(attrs={'class': 'form-control'}),
        required=True,
    )
    start_date = forms.DateField(
        widget=forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'Date From'}),
        required=False
    )
    end_date = forms.DateField(
        widget=forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'Date To'}),
        required=False
    )
    loan_category = forms.ModelChoiceField(
        queryset=LoanCategory.objects.none(),
        widget=forms.Select(attrs={'class': 'form-control'}),
        required=False
    )
    loan_scheme = forms.ChoiceField(
        choices=[('all', 'All'), ('daily', 'Daily'), ('weekly', 'Weekly'), ('half_monthly', 'Half Monthly'), ('monthly', 'Monthly')],
        widget=forms.Select(attrs={'class': 'form-control'}),
        required=False
    )
    status = forms.ChoiceField(
        choices=[('all', 'All'), ('active', 'Active'), ('paid', 'Paid')],
        widget=forms.Select(attrs={'class': 'form-control'}),
        required=False
    )
    account_number = forms.CharField(
        widget=forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'Account No.'}),
        required=False
    )

    def __init__(self, *args, **kwargs):
        user = kwargs.pop('user', None)
        super(LoanOCReportForm, self).__init__(*args, **kwargs)
        
        if user:
            active_branch = ActiveBranch.objects.get(user=user).branch
            self.fields['somity'].queryset = Somity.objects.filter(branch=active_branch)
            self.fields['loan_category'].queryset = LoanCategory.objects.filter(branch=active_branch)


class UESReportForm(forms.Form):
    start_date = forms.DateField(
        widget=forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'Date From'}),
        required=False
    )
    end_date = forms.DateField(
        widget=forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'Date To'}),
        required=False
    )
    staff = forms.ModelChoiceField(
        queryset=CustomUser.objects.none(),
        widget=forms.Select(attrs={'class': 'form-control'}),
        required=False
    )

    def __init__(self, *args, **kwargs):
        user = kwargs.pop('user', None)
        super(UESReportForm, self).__init__(*args, **kwargs)
        
        if user:
            active_branch = ActiveBranch.objects.get(user=user).branch
            self.fields['staff'].queryset = CustomUser.objects.filter(branch=active_branch)
    

class UWESReportForm(forms.Form):

templates/report/ProfitLoss.html
{% extends 'base.html' %}
{% load static %}
{% block title %}Profit & Loss Report{% endblock %}
{% block style_links %}
<link rel="stylesheet" href="{% static 'report/styles.css' %}">
<link rel="stylesheet" href="https://code.jquery.com/ui/1.13.2/themes/base/jquery-ui.css">
{% endblock %}
{% block content %}

<div>
   <h2>Profit & Loss Report</h2>
</div>

<div class="box">
    <form method="POST" action="{% url 'ProfitLoss' %}">
        {% csrf_token %}
        <div>
            {{ form.as_p }}
            <input type="submit" value="Report" name="search">
        </div>
    </form>
</div>


{% endblock %}

{% block scripts %}
<script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
<script src="https://code.jquery.com/ui/1.13.2/jquery-ui.js"></script>
<script>
    $(function() {
        $("#id_start_date").datepicker({
            dateFormat: "yy-mm-dd",
            defaultDate: null,
            placeholder: "yyyy-mm-dd",
        }).attr("placeholder", "yyyy-mm-dd");

        $("#id_end_date").datepicker({
            dateFormat: "yy-mm-dd",
            defaultDate: null,
            placeholder: "yyyy-mm-dd",
        }).attr("placeholder", "yyyy-mm-dd");
    });
</script>
{% endblock %}

templates/report/account_statment.html
{% extends 'base.html' %}
{% load static %}
{% block title %}Account Statment{% endblock %}
{% block style_links %}
<link rel="stylesheet" href="{% static 'report/styles.css' %}">
<link rel="stylesheet" href="https://code.jquery.com/ui/1.13.2/themes/base/jquery-ui.css">
{% endblock %}
{% block content %}

<div>
   <h2>Account Statment</h2>
</div>

<div class="box">
    <form method="POST" action="{% url 'account_statement' %}">
        {% csrf_token %}
        <div>
            {{ form.as_p }}
            <input type="submit" value="Report" name="search">
        </div>
    </form>
</div>


{% endblock %}

{% block scripts %}
<script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
<script src="https://code.jquery.com/ui/1.13.2/jquery-ui.js"></script>
<script>
    $(function() {
        $("#id_start_date").datepicker({
            dateFormat: "yy-mm-dd",
            defaultDate: null,
            placeholder: "yyyy-mm-dd",
        }).attr("placeholder", "yyyy-mm-dd");

        $("#id_end_date").datepicker({
            dateFormat: "yy-mm-dd",
            defaultDate: null,
            placeholder: "yyyy-mm-dd",
        }).attr("placeholder", "yyyy-mm-dd");
    });
</script>
{% endblock %}

templates/report/general_ledger.html
{% extends 'base.html' %}
{% load static %}
{% block title %}General Ledger{% endblock %}
{% block style_links %}
<link rel="stylesheet" href="{% static 'report/styles.css' %}">
<link rel="stylesheet" href="https://code.jquery.com/ui/1.13.2/themes/base/jquery-ui.css">
{% endblock %}
{% block content %}

<div>
   <h2>General Ledger</h2>
</div>

<div class="box">
    <form method="POST" action="{% url 'general_ledger' %}">
        {% csrf_token %}
        <div>
            {{ form.as_p }}
            <input type="submit" value="Report" name="search">
        </div>
    </form>
</div>


{% endblock %}

{% block scripts %}
<script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
<script src="https://code.jquery.com/ui/1.13.2/jquery-ui.js"></script>
<script>
    $(function() {
        $("#id_start_date").datepicker({
            dateFormat: "yy-mm-dd",
            defaultDate: null,
            placeholder: "yyyy-mm-dd",
        }).attr("placeholder", "yyyy-mm-dd");

        $("#id_end_date").datepicker({
            dateFormat: "yy-mm-dd",
            defaultDate: null,
            placeholder: "yyyy-mm-dd",
        }).attr("placeholder", "yyyy-mm-dd");
    });
</script>
{% endblock %}

templates/report/loan_report_weekly.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Weekly Due Loan Report</title>
    <style>
        table {
            width: 100%;
            border-collapse: collapse;
        }
        table, th, td {
            border: 1px solid black;
        }
        th, td {
            padding: 8px;
            text-align: left;
        }
        @media print {
            .no-print {
                display: none;
            }
        }
    </style>
</head>
<body>
    <div style="text-align: center;">
        <h1>Samity Hisab</h1>
        <h3>INTEGRITY IS OUR HALLMARK</h3>
        <hr>
        <p>Branch Name: {{ branch.name }}</p>
        <p>Weekly Due Loan Report</p>
        <p>Date: {{ report_date }}</p>
        <hr>
    </div>

    {% if loans %}
    <table style="margin-top: 20px;">
        <thead>
            <tr>
                <th>SL</th>
                <th>Account No</th>
                <th>Customer Name</th>
                <th>Somity/Group</th>
                <th>Start Date</th>
                <th>Expire Date</th>
                <th>Principal</th>
                <th>Profit</th>
                <th>Total</th>
                <th>Total Paid</th>
                <th>Inst.</th>
                <th>Inst. Amt</th>
                <th>Due</th>
            </tr>
        </thead>
        <tbody>
            {% for loan in loans %}
            <tr>
                <td>{{ forloop.counter }}</td>
                <td>{{ loan.customer.account_no }}</td>
                <td>{{ loan.customer.customer_name }}</td>
                <td>{{ loan.customer.group.group_name }}</td>
                <td>{{ loan.start_date|date:"d-M-Y" }}</td>
                <td>{{ loan.end_date|date:"d-M-Y" }}</td>
                <td>{{ loan.loan_amount }}</td>
                <td>{{ loan.profit_taka }}</td>
                <td>{{ loan.total_amount }}</td>
                <td>{{ loan.paid_amount }}</td>
                <td>{{ loan.paid_installments }}/{{ loan.number_of_installments }}</td>
                <td>{{ loan.installment_amount }}</td>
                <td>{{ loan.due }}</td>
            </tr>
            {% endfor %}
            <tr>
                <td colspan="6">TOTAL</td>
                <td>{{ total_loan_amount|floatformat:2 }}</td>
                <td>{{ total_profit_taka|floatformat:2 }}</td>
                <td>{{ total_total_amount|floatformat:2 }}</td>
                <td>{{ total_paid_amount|floatformat:2 }}</td>
                <td></td>
                <td>{{ total_installment_amount|floatformat:2 }}</td>
                <td>{{ total_due|floatformat:2 }}</td>
            </tr>                
        </tbody>
    </table>

    <div style="margin-top: 20px;display: flex;justify-content: space-between;">
        <p>Prepared by: _____________________</p>
        <p>Approved by: _____________________</p>
    </div>

    <div style="text-align: center; margin-top: 20px;" class="no-print">
        <button onclick="window.history.back();">Go Back</button>
        <button onclick="window.print();">Print</button>
        <button onclick="window.location.href='{% url 'home' %}';">Home</button>
    </div>
    {% endif %}

    <form method="post" class="no-print">
        {% csrf_token %}
        <div>
            <label for="id_group">Select Somity</label>
            {{ group_form.group }}
        </div>
        <button type="submit">Generate</button>
    </form>
    
</body>
</html>

templates/report/share.html
{% extends 'base.html' %}
{% load static %}
{% block title %}Share Account Report{% endblock %}
{% block style_links %}
<link rel="stylesheet" href="{% static 'report/styles.css' %}">
<link rel="stylesheet" href="https://code.jquery.com/ui/1.13.2/themes/base/jquery-ui.css">
{% endblock %}
{% block content %}

<div>
   <h2>Share Account Report</h2>
</div>

<div class="box">
    <form method="POST" action="{% url 'share_report' %}">
        {% csrf_token %}
        <div>
            {{ form.as_p }}
            <input type="submit" value="Report" name="search">
        </div>
    </form>
</div>


{% endblock %}

{% block scripts %}
<script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
<script src="https://code.jquery.com/ui/1.13.2/jquery-ui.js"></script>
<script>
    $(function() {
        var today = new Date();
        var formattedDate = $.datepicker.formatDate('yy-mm-dd', today);

        $("#id_start_date").datepicker({
            dateFormat: "yy-mm-dd",
            defaultDate: today,
        }).val(formattedDate);
        $("#id_end_date").datepicker({
            dateFormat: "yy-mm-dd",
            defaultDate: today,
        }).val(formattedDate);
    });
</script>
{% endblock %}

templates/report/ues.html
{% extends 'base.html' %}
{% load static %}
{% block title %}User Entry Summary{% endblock %}
{% block style_links %}
<link rel="stylesheet" href="{% static 'report/styles.css' %}">
<link rel="stylesheet" href="https://code.jquery.com/ui/1.13.2/themes/base/jquery-ui.css">
{% endblock %}
{% block content %}

<div>
   <h2>User Entry Summary</h2>
</div>

<div class="box">
    <form method="POST" action="{% url 'user_entry_summary' %}">
        {% csrf_token %}
        <div>
            {{ form.as_p }}
            <input type="submit" value="Report" name="search">
        </div>
    </form>
</div>


{% endblock %}

{% block scripts %}
<script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
<script src="https://code.jquery.com/ui/1.13.2/jquery-ui.js"></script>
<script>
    $(function() {
        $("#id_start_date").datepicker({
            dateFormat: "yy-mm-dd",
            defaultDate: null,
            placeholder: "yyyy-mm-dd",
        }).attr("placeholder", "yyyy-mm-dd");

        $("#id_end_date").datepicker({
            dateFormat: "yy-mm-dd",
            defaultDate: null,
            placeholder: "yyyy-mm-dd",
        }).attr("placeholder", "yyyy-mm-dd");
    });
</script>
{% endblock %}

templates/report/user_log.html
{% extends 'base.html' %}
{% load static %}
{% block title %}User Log{% endblock %}
{% block style_links %}
<link rel="stylesheet" href="{% static 'report/styles.css' %}">
<style>
    th {
        background: #0951a2;
        color: white;
    }
</style>
<link rel="stylesheet" href="https://cdn.datatables.net/2.1.3/css/dataTables.dataTables.css">
{% endblock %}

{% block content %}
<div>
    <div>
        <h2>
            User Log
        </h2>        
    </div>

    <div class="table-container">
        <table id="myTable" class="display" style="width:100%">
            <thead>
                <tr>
                    <th>SL</th>
                    <th>Timestamp</th>
                    <th>Type</th>
                    <th>Description</th>
                    <th>Branch</th>
                    <th>Users</th>
                    <th>IP Address</th>
                </tr>
            </thead>
            <tbody>
                {% for log in logs_actions %}
                <tr>
                    <td>{{ forloop.counter }}</td>
                    <td>{{ log.timestamp }}</td>
                    <td>{{ log.logs_action }}</td>
                    <td>{{ log.description }}</td>
                    <td>{{ log.branch }}</td>
                    <td>{{ log.processed_by.username}}</td>
                    <td>{{ log.ip_address}}</td>
                </tr>
                {% endfor %}
            </tbody>
        </table>
    </div>
</div>
{% endblock %}

{% block scripts %}
    <script src="https://code.jquery.com/jquery-3.7.1.js"></script>
    <script src="https://cdn.datatables.net/2.1.3/js/dataTables.js"></script>
    <script>
        $(document).ready(function() {
            $('#myTable').DataTable();
        });
    </script>
{% endblock %}