app1/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.signin, name='login'),
    path('logout/', views.signout, name='logout'),
    path('home/', views.home, name='home'),
    path('customer_home/', views.customer_home, name='customer_home'),
    path('update-active-branch/', views.update_active_branch, name='update_active_branch'),
    path('set_language/', views.set_language, name='set_language'),
    path('customer-login/', views.customer_login, name='customer_login'),
    path('customer-logout/', views.customer_signout, name='customer_logout'),
    path('customer_change_password/', views.customer_change_password, name='customer_change_password'),
    path('access-denied/', views.access_denied, name='access_denied'),

    path('manage-permissions/', views.manage_permissions, name='manage_permissions'),

    path('customers-add/', views.customer_add, name='customer_add'),
    path('customers-list/', views.customer_list, name='customer_list'),
    path('customers-details/<int:id>/', views.customer_details, name='customer_details'),
    path('customers-edit/<int:id>/', views.customer_edit, name='customer_edit'),

    path('general-list/', views.general_list, name='general_list'),
    path('general-deposit/<int:id>/', views.general_deposit, name='general_deposit'),
    path('general-withdraw/<int:id>/', views.general_withdraw, name='general_withdraw'),
    path('general-transactions/<int:id>/', views.general_transaction_history, name='general_transaction_history'),
    path('general-deposit-search/', views.general_deposit_search, name='general_deposit_search'),
    path('general-withdraw-search/', views.general_withdraw_search, name='general_withdraw_search'),

    path('savings-list/', views.savings_list, name='savings_list'),
    path('savings-deposit/<int:id>/', views.savings_deposit, name='savings_deposit'),
    path('savings-withdraw/<int:id>/', views.savings_withdraw, name='savings_withdraw'),
    path('savings-transactions/<int:id>/', views.savings_transaction_history, name='savings_transaction_history'),
    path('savings-deposit-search/', views.savings_deposit_search, name='savings_deposit_search'),
    path('savings-withdraw-search/', views.savings_withdraw_search, name='savings_withdraw_search'),

    path('loan-search/', views.loan_search, name='loan_search'),
    path('loan-list/', views.loan_list, name='loan_list'),
    path('loan-create/<str:account_no>/', views.loan_create, name='loan_create'),
    path('loan-schedule/<int:loan_id>/', views.loan_schedule, name='loan_schedule'),
    path('loan-collection/<int:loan_id>/', views.loan_collection, name='loan_collection'),
    path('loan-transaction/<int:loan_id>/', views.loan_trans, name='loan_trans'),
    path('loan-fine/<int:loan_id>/', views.loan_fine, name='loan_fine'),
    path('loan-collection-search/', views.loan_collection_search, name='loan_collection_search'),
    path('loan-close-search/', views.loan_close_search, name='loan_close_search'),
    path('loan-close/<int:loan_id>/', views.loan_close, name='loan_close'),



    path('loan-cc-search/', views.loan_cc_search, name='loan_cc_search'),
    path('loan-cc-list/', views.loan_cc_list, name='loan_cc_list'),
    path('loan-cc-create/<str:account_no>/', views.loan_cc_create, name='loan_cc_create'),
    path('loan-cc-collection/<int:loan_id>/', views.loan_cc_collection, name='loan_cc_collection'),
    path('loan-cc-transaction/<int:loan_id>/', views.loan_cc_trans, name='loan_cc_trans'),
    path('loan-cc-collection-search/', views.loan_cc_collection_search, name='loan_cc_collection_search'),
    path('loan-cc-close-search/', views.loan_cc_close_search, name='loan_cc_close_search'),
    path('loan-cc-close/<int:loan_id>/', views.loan_cc_close, name='loan_cc_close'),


    path('loan-special-search/', views.loan_sp_search, name='loan_sp_search'),
    path('loan-special-list/', views.loan_sp_list, name='loan_sp_list'),
    path('loan-special-create/<str:account_no>/', views.loan_sp_create, name='loan_sp_create'),
    path('loan-special-collection/<int:loan_id>/', views.loan_sp_collection, name='loan_sp_collection'),
    path('loan-special-close-search/', views.loan_sp_close_search, name='loan_sp_close_search'),
    path('loan-special-close/<int:loan_id>/', views.loan_sp_close, name='loan_sp_close'),



    path('dps-search/', views.dps_search, name='dps_search'),
    path('dps-list/', views.dps_list, name='dps_list'),
    path('dps-create/<str:account_no>/', views.dps_create, name='dps_create'),
    path('dps-schedule/<int:id>/', views.dps_schedule, name='dps_schedule'),
    path('dps-deposit/<int:id>/', views.dps_deposit, name='dps_deposit'),
    path('dps-withdraw/<int:id>/', views.dps_withdraw, name='dps_withdraw'),
    path('dps-transaction/<int:id>/', views.dps_transaction, name='dps_transaction'),
    path('dps-deposit-search/', views.dps_deposit_search, name='dps_deposit_search'),
    path('dps-withdraw-search/', views.dps_withdraw_search, name='dps_withdraw_search'),
    path('dps-close-search/', views.dps_close_search, name='dps_close_search'),
    path('dps-close/<int:id>/', views.dps_close, name='dps_close'),

    path('fdr-search/', views.fdr_search, name='fdr_search'),
    path('fdr-list/', views.fdr_list, name='fdr_list'),
    path('fdr-create/<str:account_no>/', views.fdr_create, name='fdr_create'),
    path('fdr-deposit/<int:id>/', views.fdr_deposit, name='fdr_deposit'),
    path('fdr-withdraw/<int:id>/', views.fdr_withdraw, name='fdr_withdraw'),
    path('fdr-profit-withdraw/<int:id>/', views.fdr_profit_withdraw, name='fdr_profit_withdraw'),
    path('fdr-transactions/<int:id>/', views.fdr_transaction_history, name='fdr_transaction_history'),
    path('fdr-profit/<int:id>/', views.fdr_profit, name='fdr_profit'),
    path('fdr-deposit-search/', views.fdr_deposit_search, name='fdr_deposit_search'),
    path('fdr-profit-withdraw-search/', views.fdr_profit_withdraw_search, name='fdr_profit_withdraw_search'),
    path('fdr-balance-withdraw-search/', views.fdr_balance_withdraw_search, name='fdr_balance_withdraw_search'),
    path('fdr-close-search/', views.fdr_close_search, name='fdr_close_search'),
    path('fdr-close/<int:id>/', views.fdr_close, name='fdr_close'),

    path('share-list/', views.share_list, name='share_list'),
    path('share-create/<str:account_no>/', views.share_create, name='share_create'),
    path('share-search/', views.share_search, name='share_search'),
    path('share-deposit/<int:share_id>/', views.share_deposit, name='share_deposit'),
    path('share-deposit-search/', views.share_deposit_search, name='share_deposit_search'),
    path('share-withdraw-search/', views.share_withdraw_search, name='share_withdraw_search'),
    path('share-profit-withdraw-search/', views.share_profit_withdraw_search, name='share_profit_withdraw_search'),
    path('share-withdraw/<int:share_id>/', views.share_withdraw, name='share_withdraw'),
    path('share-transfer/<int:share_id>/', views.share_transfer, name='share_transfer'),
    path('share-profit-withdraw/<int:share_id>/', views.share_profit_withdraw, name='share_profit_withdraw'),
    path('share-transaction-history/<int:share_id>/', views.share_transaction_history, name='share_transaction_history'),

    path('bank_withdraw/', views.bank_withdraw, name='bank_withdraw'),
    path('bank_deposit/', views.bank_deposit, name='bank_deposit'),
    path('package/', views.package, name='package'),

    path('delete-search/', views.delete_search, name='delete_search'),
    path('delete-customer/<int:id>/', views.delete_customer, name='delete_customer'),
    path('delete-loan/<int:id>/', views.loan_delete, name='loan_delete'),
    path('delete-loan-cc/<int:id>/', views.loan_cc_delete, name='loan_cc_delete'),
    path('delete-loan-sp/<int:id>/', views.loan_sp_delete, name='loan_sp_delete'),
    path('delete-dps/<int:id>/', views.dps_delete, name='dps_delete'),
    path('delete-fdr/<int:id>/', views.fdr_delete, name='fdr_delete'),
    path('delete-share/<int:share_id>/', views.share_delete, name='share_delete'),

    path('somity_wise_dps_deposit/', views.somity_wise_dps_deposit, name='somity_wise_dps_deposit'),
    path('somity_wise_general_deposit/', views.somity_wise_general_deposit, name='somity_wise_general_deposit'),
    path('somity_wise_loan/', views.somity_wise_loan, name='somity_wise_loan'),
    path('common_collection/', views.common_collection, name='common_collection'),
]

project/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('app1.urls')),
    path('', include('primary_setup.urls')),
    path('', include('otrans.urls')),
    path('report/', include('report.urls')),
    path('sheet/', include('sheet.urls')),
    path('dashboard/', include('dashboard.urls')),
    path('sms/', include('sms.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

sms/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('sms_single/', views.sms_single, name='sms_single'),
    path('sms_bulk/', views.sms_bulk, name='sms_bulk'),
    path('sms_customer/', views.sms_customer, name='sms_customer'),
    path('sms_report/', views.sms_report, name='sms_report'),
]

otrans/models.py
from datetime import date, timezone
import random
import string
from django.db import models
from primary_setup.models import OutLoan, Somity, Branch, Director, CustomUser, VoucherCategory
from django.utils import timezone


class Expense(models.Model):
    
    branch = models.ForeignKey(Branch, on_delete=models.CASCADE)
    somity = models.ForeignKey(Somity, on_delete=models.CASCADE)
    
    # category = models.CharField(max_length=50, choices=CATEGORY_CHOICES)

    voucher_category = models.ForeignKey(VoucherCategory, on_delete=models.CASCADE)
    CustomerName = models.CharField(max_length=100)
    VoucherID = models.CharField(max_length=50, editable=False, unique=True)
    Amount = models.DecimalField(max_digits=10, decimal_places=2)
    ExpenseBy = models.CharField(max_length=50)
    IsCalculateWithLossProfit = models.BooleanField()
    ExpenseDate = models.DateField()
    Note = models.CharField(max_length=200, null=True, blank=True)

class Income(models.Model):

    branch = models.ForeignKey(Branch, on_delete=models.CASCADE)
    somity = models.ForeignKey(Somity, on_delete=models.CASCADE)
    
    # category = models.CharField(max_length=50, choices=CATEGORY_CHOICES)

    voucher_category = models.ForeignKey(VoucherCategory, on_delete=models.CASCADE)
    CustomerName = models.CharField(max_length=100)
    VoucherID = models.CharField(max_length=50, editable=False, unique=True)
    Amount = models.DecimalField(max_digits=10, decimal_places=2)
    IncomeBy = models.CharField(max_length=50)
    IsCalculateWithLossProfit = models.BooleanField()
    IncomeDate = models.DateField()
    Note = models.CharField(max_length=200, null=True, blank=True)


class Deposit(models.Model):
    branch = models.ForeignKey(Branch, on_delete=models.CASCADE)
    director = models.ForeignKey(Director, on_delete=models.CASCADE)
    processed_by = models.CharField(max_length=50, null=True, blank=True)

    Date = models.DateField()
    VoucherID = models.CharField(max_length=50, editable=False, unique=True)
    Amount = models.DecimalField(max_digits=10, decimal_places=2)
    Note = models.CharField(max_length=200, null=True, blank=True)


class Withdraw(models.Model):
    branch = models.ForeignKey(Branch, on_delete=models.CASCADE)
    director = models.ForeignKey(Director, on_delete=models.CASCADE)
    processed_by = models.CharField(max_length=50, null=True, blank=True)

    Date = models.DateField()
    VoucherID = models.CharField(max_length=50, editable=False, unique=True)
    Amount = models.DecimalField(max_digits=10, decimal_places=2)
    Note = models.CharField(max_length=200, null=True, blank=True)


class Passbook(models.Model):
    branch = models.ForeignKey(Branch, on_delete=models.CASCADE)
    customer = models.ForeignKey('app1.Customer', on_delete=models.CASCADE)
    Account = models.CharField(max_length=200)
    Category = models.CharField(max_length=200, null=True, blank=True)
    processed_by = models.CharField(max_length=50, null=True, blank=True)
    Date = models.DateField()
    Amount = models.DecimalField(max_digits=10, decimal_places=2)
    Note = models.CharField(max_length=200, null=True, blank=True)
    VoucherID = models.CharField(max_length=50, editable=False, unique=True, null=True, blank=True)

    def save(self, *args, **kwargs):            
        if not self.Date:
            self.Date = timezone.now().date()
        super().save(*args, **kwargs)


class SSM_Deposit(models.Model):
    branch = models.ForeignKey(Branch, on_delete=models.CASCADE)
    staff = models.ForeignKey(CustomUser, on_delete=models.CASCADE)
    processed_by = models.CharField(max_length=50, null=True, blank=True)

    Date = models.DateField()
    VoucherID = models.CharField(max_length=50, editable=False, unique=True)
    Amount = models.DecimalField(max_digits=10, decimal_places=2)
    Note = models.CharField(max_length=200, null=True, blank=True)


class SSM_Withdraw(models.Model):
    branch = models.ForeignKey(Branch, on_delete=models.CASCADE)
    staff = models.ForeignKey(CustomUser, on_delete=models.CASCADE)
    processed_by = models.CharField(max_length=50, null=True, blank=True)

    Date = models.DateField()
    VoucherID = models.CharField(max_length=50, editable=False, unique=True)
    Amount = models.DecimalField(max_digits=10, decimal_places=2)
    Note = models.CharField(max_length=200, null=True, blank=True)


class GetOutLoan(models.Model):

    branch = models.ForeignKey(Branch, on_delete=models.CASCADE)
    account = models.ForeignKey(OutLoan, on_delete=models.CASCADE)
    date = models.DateField()
    current_amount = models.DecimalField(max_digits=10, decimal_places=2, default=0)
    deposit_amount = models.DecimalField(max_digits=10, decimal_places=2, default=0)
    profit = models.DecimalField(max_digits=10, decimal_places=2, blank=True, null=True, default=0)
    note = models.TextField(blank=True, null=True)
    processed_by = models.CharField(max_length=50, null=True, blank=True)
    VoucherID = models.CharField(max_length=50, editable=False, unique=True)

    def save(self, *args, **kwargs):
        if not self.VoucherID:
            self.VoucherID = ''.join(random.choices(string.ascii_lowercase + string.digits, k=15))
        if self.date is None:
            self.date = timezone.now().date()
        super().save(*args, **kwargs)
        
    def __str__(self):
        return f"{self.account} - {self.deposit_amount}"


class Salary(models.Model):
    branch = models.ForeignKey(Branch, on_delete=models.CASCADE)
    date = models.DateField()
    year = models.PositiveIntegerField()
    month = models.CharField(max_length=100)
    staff_name = models.CharField(max_length=100)
    basic_salary = models.DecimalField(max_digits=10, decimal_places=2)
    others = models.DecimalField(max_digits=10, decimal_places=2, default=0)
    bonus = models.DecimalField(max_digits=10, decimal_places=2, default=0)
    deduction = models.DecimalField(max_digits=10, decimal_places=2, default=0)
    payable = models.DecimalField(max_digits=10, decimal_places=2, editable=False)
    processed_by = models.CharField(max_length=50, null=True, blank=True)

    def save(self, *args, **kwargs):
        if not self.date:
            self.date = date.today()
        self.payable = self.basic_salary + self.others + self.bonus - self.deduction
        super().save(*args, **kwargs)

    def __str__(self):
        return f'{self.staff_name} - {self.year}/{self.month}'



class ProfitDistribution(models.Model):
    branch = models.ForeignKey(Branch, on_delete=models.CASCADE)
    date = models.DateField()
    financial_year = models.CharField(max_length=20, default='July-June')
    year = models.CharField(max_length=9)
    profit_type = models.CharField(max_length=50)
    profit_percentage = models.DecimalField(max_digits=5, decimal_places=2)
    total_account = models.PositiveIntegerField()
    profit_amount = models.DecimalField(max_digits=12, decimal_places=2, default=0.00)
    process_by = models.CharField(max_length=100, default='Admin')

    def __str__(self):
        return f"{self.date} - {self.profit_type}"
    

templates/app1/dps/dps_create.html
{% extends 'base.html' %}
{% load static %}
{% block title %}Add DPS{% endblock %}
{% block style_links %}
<link rel="stylesheet" href="{% static 'app1/customer_details.css' %}">
<link rel="stylesheet" href="{% static 'app1/dps.css' %}">
<link rel="stylesheet" href="https://code.jquery.com/ui/1.13.2/themes/base/jquery-ui.css">
<script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
<script src="https://code.jquery.com/ui/1.13.2/jquery-ui.js"></script>

<script>
    document.addEventListener('DOMContentLoaded', function() {
        // Retrieve and parse the JSON data from the Django template
        const dpsSchemes = JSON.parse(document.getElementById('dps-schemes-data').textContent);

        const schemeSelect = document.getElementById('id_dps_scheme');
        const installmentSequenceInput = document.getElementById('id_installment_sequence');

        // Function to update installment sequence based on selected scheme
        function updateInstallmentSequence() {
            const selectedSchemeId = parseInt(schemeSelect.value);
            const selectedScheme = dpsSchemes.find(scheme => scheme.id === selectedSchemeId);

            if (selectedScheme) {
                installmentSequenceInput.value = selectedScheme.payment_sequence;
            }
        }

        // Event listener for scheme change
        schemeSelect.addEventListener('change', updateInstallmentSequence);

        // Update installment sequence on page load based on the initially selected scheme
        updateInstallmentSequence();
    });
</script>

{% endblock %}

{% block content %}
<h2>Add DPS</h2>
<div class="div1">
    <table>
        <tr>
            <th>Account No.</th>
            <td>{{ customer.account_no }}</td>
        </tr>
        <tr>
            <th>Customer Name</th>
            <td>{{ customer.customer_name }}</td>
        </tr>
        <tr>
            <th>Parents</th>
            <td>{{ customer.customer_father }}/{{ customer.customer_mother }}</td>
        </tr>
        <tr>
            <th>Mobile Number</th>
            <td>{{ customer.mobile_number }}</td>
        </tr>
        <tr>
            <th>Customer Type</th>
            <td>{{ customer.customer_type }}</td>
        </tr>
        <tr>
            <th>Somity/Group</th>
            <td>{{ customer.group }}</td>
        </tr>
        <tr>
            <th>Current Address</th>
            <td>{{ customer.current_village }}, {{ customer.current_post_office }}, {{ customer.current_thana }}, {{ customer.current_district }}</td>
        </tr>
        <tr>
            <th>Permanent Address</th>
            <td>{{ customer.permanent_village }}, {{ customer.permanent_post_office }}, {{ customer.permanent_thana }}, {{ customer.permanent_district }}</td>
        </tr>
    </table>
    
    <div class="img-container">
        {% if customer.profile_picture %}
        <div>
            <img src="{{ customer.profile_picture.url }}" class="centered-image">
        </div>
        {% endif %}
    </div>
</div>
<div class="div2">
    <form method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit">Submit</button>
    </form>
</div>
<div>
    {{ dps_schemes|json_script:"dps-schemes-data" }}
</div>
{% endblock %}

{% block scripts %}
<script>
    function calculateValues() {
        const amount_per_installments = parseFloat(document.getElementById('id_amount_per_installments').value) || 0;
        const number_of_installments = parseFloat(document.getElementById('id_number_of_installments').value) || 0;
        const profitPercent = parseFloat(document.getElementById('id_profit_percent').value) || 0;
        const schemeId = document.getElementById('id_dps_scheme').value;

        // Calculate Profit Taka
        const totalAmountWithoutProfit = amount_per_installments * number_of_installments;
        const profitTaka = totalAmountWithoutProfit * (profitPercent / 100);
        document.getElementById('id_profit_taka').value = profitTaka.toFixed(2);

        // Calculate Total Amount
        const totalAmount = totalAmountWithoutProfit + profitTaka;
        document.getElementById('id_total_amount').value = totalAmount.toFixed(2);

        // Set Installment Sequence based on selected scheme
        let installmentSequence = '';
        if (schemeId) {
            const scheme = dpsSchemes.find(s => s.id === parseInt(schemeId));
            if (scheme) {
                installmentSequence = scheme.payment_sequence;
            }
        }
        document.getElementById('id_installment_sequence').value = installmentSequence;
    }

    document.getElementById('id_amount_per_installments').addEventListener('input', calculateValues);
    document.getElementById('id_number_of_installments').addEventListener('input', calculateValues);
    document.getElementById('id_profit_percent').addEventListener('input', calculateValues);
    
</script>

<script>
    $(function() {
        var today = new Date();
        var formattedDate = $.datepicker.formatDate('yy-mm-dd', today);

        $("#id_created_date").datepicker({
            dateFormat: "yy-mm-dd",
            defaultDate: today,
        }).val(formattedDate);
    });
</script>
{% endblock %}

templates/app1/dps/dps_cs.html
{% extends 'base.html' %}
{% load static %}
{% block title %}DPS Close{% endblock %}
{% block style_links %}
<link rel="stylesheet" href="{% static 'app1/add_loan1.css' %}">
{% endblock %}

{% block content %}
<h2>DPS Closing</h2>
<div class="div1">
    <form method="post"> {% csrf_token %}

        <div>
            <input type="text" id="account_no" name="account_no" placeholder="Account No." required>
        </div>
        <div>
           <button type="submit">Search</button> 
        </div>
    </form>
    
      {% if error %}
        <p style="color:red;">{{ error }}</p>
      {% endif %}
</div>
{% endblock %}

{% block scripts %}
{% endblock %}

templates/app1/dps/dps_deposit.html
{% extends 'base.html' %}
{% load static %}
{% block title %}DPS Deposit{% endblock %}
{% block style_links %}
<link rel="stylesheet" href="{% static 'app1/dps.css' %}">
<link rel="stylesheet" href="https://code.jquery.com/ui/1.13.2/themes/base/jquery-ui.css">
{% endblock %}

{% block content %}

    <h2>DPS Deposit: {{ dps.transaction_id }}</h2>

    <div class="table-container">
        <table id="myTabl" class="display" style="width:100%">
            <thead>
                <tr>
                    <th>DPS Scheme</th>
                    <th>Account No</th>
                    <th>Customer Name</th>
                    <th>Start Date</th>
                    <th>End Date</th>
                    <th>profit</th>
                    <th>Installments</th>
                    <th>Installments Amount</th>
                    <th>Total Amount</th>
                    <th>Balance</th>
                    <th>Status</th>
                </tr>
            </thead>
            <tbody>
                <tr>
                    <td>{{ dps.dps_scheme }}</td>
                    <td>{{ dps.customer.account_no }}</td>
                    <td>{{ dps.customer.customer_name }}</td>
                    <td>{{ dps.start_date }}</td>
                    <td>{{ dps.end_date }}</td>
                    <td>{{ dps.profit_percent }}%</td>
                    <td>{{ dps.number_of_installments }}</td>
                    <td>{{ dps.amount_per_installments }}</td>
                    <td>{{ dps.total_amount }}</td>
                    <td>{{ dps.balance }}</td>
                    <td>{{ dps.customer.status }}</td>
                </tr>
            </tbody>
        </table>
    </div>

    <div class="div2">
        <form action="#">
            <label for="">Amount Per Installment</label>
            <input type="text" value="{{ dps.amount_per_installments }}" readonly>
            <label for="">Target</label>
            <input type="text" value="{{ dps.total_amount }}" readonly>
            <label for="">Balance</label>
            <input type="text" value="{{ dps.balance }}" readonly>
        </form>

        <form method="post">
            {% csrf_token %}
            {{ form.as_p }}
            <button type="submit">Submit Collection</button>
        </form>
    </div>

{% endblock %}

{% block scripts %}
    <script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
    <script src="https://code.jquery.com/ui/1.13.2/jquery-ui.js"></script>

    <script>
        $(function() {
            var today = new Date();
            var formattedDate = $.datepicker.formatDate('yy-mm-dd', today);
    
            $("#id_Date").datepicker({
                dateFormat: "yy-mm-dd",
                defaultDate: today,
            }).val(formattedDate);
        });
    </script>
{% endblock %}

templates/app1/dps/dps_withdraw.html
{% extends 'base.html' %}
{% load static %}
{% block title %}DPS Withdraw{% endblock %}
{% block style_links %}
<link rel="stylesheet" href="{% static 'app1/dps.css' %}">
<link rel="stylesheet" href="https://code.jquery.com/ui/1.13.2/themes/base/jquery-ui.css">
{% endblock %}

{% block content %}

    <h2>DPS Withdraw: {{ dps.transaction_id }}</h2>

    <div class="table-container">
        <table id="myTabl" class="display" style="width:100%">
            <thead>
                <tr>
                    <th>DPS Scheme</th>
                    <th>Account No</th>
                    <th>Customer Name</th>
                    <th>Start Date</th>
                    <th>End Date</th>
                    <th>profit</th>
                    <th>Installments</th>
                    <th>Installments Amount</th>
                    <th>Total Amount</th>
                    <th>Balance</th>
                    <th>Status</th>
                </tr>
            </thead>
            <tbody>
                <tr>
                    <td>{{ dps.dps_scheme }}</td>
                    <td>{{ dps.customer.account_no }}</td>
                    <td>{{ dps.customer.customer_name }}</td>
                    <td>{{ dps.start_date }}</td>
                    <td>{{ dps.end_date }}</td>
                    <td>{{ dps.profit_percent }}%</td>
                    <td>{{ dps.number_of_installments }}</td>
                    <td>{{ dps.amount_per_installments }}</td>
                    <td>{{ dps.total_amount }}</td>
                    <td>{{ dps.balance }}</td>
                    <td>{{ dps.customer.status }}</td>
                </tr>
            </tbody>
        </table>
    </div>

    <div class="div2">
        <form action="#">
            <label for="">Amount Per Installment</label>
            <input type="text" value="{{ dps.amount_per_installments }}" readonly>
            <label for="">Target</label>
            <input type="text" value="{{ dps.total_amount }}" readonly>
            <label for="">Balance</label>
            <input type="text" value="{{ dps.balance }}" readonly>
        </form>

        <form method="post">
            {% csrf_token %}
            {{ form.as_p }}
            <button type="submit">Submit</button>
        </form>
    </div>

{% endblock %}

{% block scripts %}
    <script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
    <script src="https://code.jquery.com/ui/1.13.2/jquery-ui.js"></script>

    <script>
        $(function() {
            var today = new Date();
            var formattedDate = $.datepicker.formatDate('yy-mm-dd', today);
    
            $("#id_Date").datepicker({
                dateFormat: "yy-mm-dd",
                defaultDate: today,
            }).val(formattedDate);
        });
    </script>
{% endblock %}